/* PlantenTrainer — soorten van de tweede reeks geslachten.
   Zelfde opzet en woordenschat als soortdata.js. */

const SOORTDATA2 = [

/* ══════════ BERBERIS — zuurbes ══════════ */
{ id:"berberis-thunbergii", g:"Berberis", s:"thunbergii", nl:"Japanse zuurbes",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"1–1,5 m", breedte:"1–1,5 m",
  blad:"Bladverliezend", bloeitijd:"April–mei", bloeikleur:"Geel met rood",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Lage haag","Massief","Kleurblad"],
  onderscheid:"<b>Enkelvoudige doorns</b>, niet drietandig, en <b>klein spatelvormig gaafrandig blad</b> in bundeltjes. Felrode herfstkleur en langwerpige rode bessen.",
  weetje:"Veruit de meest geplante zuurbes, vooral in roodbladige vormen. In Noord-Amerika geldt hij als invasief." },

{ id:"berberis-julianae", g:"Berberis", s:"julianae", nl:"Wintergroene zuurbes",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"1,5–2,5 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Geel, in bundels",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Haag","Afscherming","Scherm"],
  onderscheid:"<b>Lang, smal, leerachtig wintergroen blad met scherpe stekeltanden langs de rand</b>, en zeer stevige drietandige doorns. De meest doornige van allemaal.",
  weetje:"Als afscheiding vrijwel ondoordringbaar; wordt daarom om speelterreinen en langs spoorwegen geplant." },

{ id:"berberis-darwinii", g:"Berberis", s:"darwinii", nl:"Darwins zuurbes",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"1,5–2,5 m", breedte:"1,5–2 m",
  blad:"Bladhoudend", bloeitijd:"April–mei", bloeikleur:"Oranje tot goudoranje",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Haag","Solitair","Border"],
  onderscheid:"<b>Klein glanzend blad met drie stekelpunten aan de top</b>, als een miniatuurhulst. En de bloei is <b>oranje</b>, niet geel — dat heeft geen enkele andere.",
  weetje:"Ontdekt door Charles Darwin tijdens de reis van de Beagle; vandaar de naam." },

{ id:"berberis-x-stenophylla", g:"Berberis", s:"× stenophylla", nl:"Smalbladige zuurbes",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Bladhoudend", bloeitijd:"April–mei", bloeikleur:"Goudgeel, overvloedig",
  groeivorm:"Heester", groei:"Snel", gebruik:["Haag","Solitair","Bijenplant"],
  onderscheid:"<b>Zeer smal, bijna lijnvormig wintergroen blad</b> op lange, diep overhangende takken die in april helemaal geel kleuren van de bloemen.",
  weetje:"Kruising van <i>darwinii</i> en <i>empetrifolia</i>; in bloei een van de opvallendste bijenplanten van het voorjaar." },

{ id:"berberis-vulgaris", g:"Berberis", s:"vulgaris", nl:"Gewone zuurbes",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"2–3 m", breedte:"1,5–2,5 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Geel, hangende trossen",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Landschap","Haag","Vogelbosje"],
  onderscheid:"De <b>enige inheemse</b> soort. Ovaal blad met een <b>fijn gezaagde rand</b> en <b>hangende trossen van vijftien tot vijfentwintig bloemen</b> — geen bundeltjes.",
  weetje:"Waardplant voor zwarte roest in graan. In graanstreken werd hij daarom eeuwenlang systematisch uitgeroeid." },

{ id:"berberis-candidula", g:"Berberis", s:"candidula", nl:"Kruipende zuurbes",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"0,3–0,5 m", breedte:"0,8–1,2 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Helder geel, alleenstaand",
  groeivorm:"Bodembedekker", groei:"Traag", gebruik:["Bodembedekker","Randbeplanting","Talud"],
  onderscheid:"<b>Laag kussenvormig dwergstruikje</b> met klein glanzend blad dat aan de <b>onderkant opvallend wit</b> is. De laagste van het geslacht.",
  weetje:"Bloemen staan hier alleen in plaats van in trosjes; bij twijfel tussen de lage soorten is dat het kenmerk." },

{ id:"berberis-verruculosa", g:"Berberis", s:"verruculosa", nl:"Wrattige zuurbes",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"1–1,5 m", breedte:"1–1,5 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Goudgeel",
  groeivorm:"Heester", groei:"Traag", gebruik:["Lage haag","Border","Massief"],
  onderscheid:"<b>Twijgen bezaaid met fijne wratjes</b> — voel er met je vingers over. Blad klein, glanzend donkergroen, wit aan de onderkant, stijf opgaande struik.",
  weetje:"Verkleurt in de winter bronsrood terwijl hij zijn blad houdt; heel decoratief in december." },

{ id:"berberis-wilsoniae", g:"Berberis", s:"wilsoniae", nl:"Wilsons zuurbes",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"0,8–1,2 m", breedte:"1–1,5 m",
  blad:"Halfbladhoudend", bloeitijd:"Juni", bloeikleur:"Bleekgeel",
  groeivorm:"Heester", groei:"Traag", gebruik:["Border","Massief","Herfstkleur"],
  onderscheid:"<b>Dichte bundels heel klein blauwgroen blad</b> en daarna <b>koraalroze tot zalmkleurige bessen</b> — geen enkele andere zuurbes heeft die kleur.",
  weetje:"De herfstkleur is oranjerood en valt samen met de bessen; dan is dit de mooiste van het geslacht." },

{ id:"berberis-x-ottawensis", g:"Berberis", s:"× ottawensis", nl:"Ottawa-zuurbes",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"2–2,5 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Geel met rood",
  groeivorm:"Heester", groei:"Snel", gebruik:["Haag","Solitair","Kleurblad"],
  onderscheid:"<b>Als een uit de kluiten gewassen <i>thunbergii</i></b>: zelfde vorm maar duidelijk groter blad en tot een meter hoger. Kruising met de gewone zuurbes.",
  weetje:"Wordt vaak verkocht onder de cultivarnaam <i>'Superba'</i>; groeit merkbaar forser dan een gewone rode zuurbes." },

{ id:"berberis-gagnepainii", g:"Berberis", s:"gagnepainii", nl:"Gagnepains zuurbes",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"1,5–2 m", breedte:"1,5–2 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Goudgeel",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Haag","Afscherming","Massief"],
  onderscheid:"Lang smal wintergroen blad met een <b>sterk gegolfde, stekelig getande rand</b>, en <b>mat</b> in plaats van glanzend. Dat matte verschil met <i>julianae</i> is het kenmerk.",
  weetje:"Verdraagt schaduw beter dan de andere wintergroene zuurbessen en blijft daar toch dicht." },

/* ══════════ SPIRAEA — spirea ══════════ */
{ id:"spiraea-japonica", g:"Spiraea", s:"japonica", nl:"Japanse spirea",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"0,6–1,5 m", breedte:"0,8–1,2 m",
  blad:"Bladverliezend", bloeitijd:"Juli–september", bloeikleur:"Roze, plat scherm",
  groeivorm:"Heester", groei:"Snel", gebruik:["Border","Massief","Lage haag"],
  onderscheid:"<b>Platte roze schermen in de zomer</b> op de toppen van het nieuwe hout. De bekendste zomerbloeier van het geslacht.",
  weetje:"Bloeit op nieuw hout: in maart hard terugzetten tot 20 cm geeft juist de rijkste bloei." },

{ id:"spiraea-nipponica", g:"Spiraea", s:"nipponica", nl:"Nippon-spirea",
  standplaats:"Volle zon", water:"Normaal", hoogte:"1,5–2 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"Juni", bloeikleur:"Wit, halfbolvormige schermpjes",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Solitair","Haag","Massief"],
  onderscheid:"<b>Halfbolvormige witte schermpjes dicht op elkaar langs de hele boogvormige tak</b>, in juni. Blad klein en breed afgerond.",
  weetje:"Bloeit op oud hout: snoei meteen na de bloei, anders snoei je de knoppen voor volgend jaar weg." },

{ id:"spiraea-x-arguta", g:"Spiraea", s:"× arguta", nl:"Bruidsluier",
  standplaats:"Volle zon", water:"Normaal", hoogte:"1,5–2 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"April–mei", bloeikleur:"Zuiver wit",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Solitair","Border","Haag"],
  onderscheid:"<b>Een wolk van wit in april</b> op zeer dunne, diep overhangende twijgen, met <b>heel smal fijn blad</b>. De sierlijkste van het geslacht.",
  weetje:"De naam bruidsluier zegt alles: in volle bloei lijkt de struik met witte kant bedekt." },

{ id:"spiraea-thunbergii", g:"Spiraea", s:"thunbergii", nl:"Thunbergs spirea",
  standplaats:"Volle zon", water:"Normaal", hoogte:"1–1,5 m", breedte:"1–1,5 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Wit, op kale twijgen",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Border","Voorjaarsbloei","Massief"],
  onderscheid:"<b>De allervroegste</b>: bloeit al eind maart op nog kale twijgen. Blad daarna <b>extreem smal en lijnvormig</b>, lichtgroen, met gele herfstkleur.",
  weetje:"Een van de eerste heesters die bloeit; belangrijk voor hommelkoninginnen die net ontwaakt zijn." },

{ id:"spiraea-betulifolia", g:"Spiraea", s:"betulifolia", nl:"Berkbladige spirea",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"0,6–1 m", breedte:"0,8–1,2 m",
  blad:"Bladverliezend", bloeitijd:"Juni", bloeikleur:"Wit, vlak scherm",
  groeivorm:"Heester", groei:"Traag", gebruik:["Lage haag","Border","Massief"],
  onderscheid:"<b>Breed, rond, grof gezaagd blad als van een berk</b> — veel breder dan bij alle andere spirea's. Compacte bol met vlakke witte schermen.",
  weetje:"De herfstkleur is oranje tot wijnrood en houdt lang aan; daarom in opmars in openbaar groen." },

{ id:"spiraea-douglasii", g:"Spiraea", s:"douglasii", nl:"Douglas-spirea",
  standplaats:"Volle zon", water:"Normaal tot vochtig", hoogte:"1,5–2 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"Juli–augustus", bloeikleur:"Donkerroze, rechte pluim",
  groeivorm:"Heester", groei:"Snel", gebruik:["Oever","Massief","Landschap"],
  onderscheid:"<b>Rechtopstaande donkerroze pluim</b> in plaats van een plat scherm, en blad dat <b>grijsviltig behaard is aan de onderkant</b>. Vormt uitlopers.",
  weetje:"Verwildert op vochtige heide en in natuurgebied; daar geldt hij als ongewenste exoot." },

{ id:"spiraea-salicifolia", g:"Spiraea", s:"salicifolia", nl:"Wilgbladige spirea",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"1–2 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"Juni–augustus", bloeikleur:"Lichtroze pluim",
  groeivorm:"Heester", groei:"Snel", gebruik:["Oever","Landschap","Massief"],
  onderscheid:"<b>Lang smal wilgachtig blad</b> dat aan beide zijden kaal en groen is, met smalle roze pluimen. Woekert sterk met wortelopslag.",
  weetje:"Door die uitlopers vormt hij dichte velden; handig voor taludvastlegging, lastig in een border." },

{ id:"spiraea-x-vanhouttei", g:"Spiraea", s:"× vanhouttei", nl:"Pronkspirea",
  standplaats:"Volle zon", water:"Normaal", hoogte:"2–2,5 m", breedte:"2–2,5 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Wit, bolvormige schermpjes",
  groeivorm:"Heester", groei:"Snel", gebruik:["Solitair","Haag","Massief"],
  onderscheid:"De <b>grootste</b> van het geslacht, met <b>diep overhangende takken vol witte schermpjes</b> en <b>blauwgroen, licht gelobd ruitvormig blad</b>.",
  weetje:"Genoemd naar de Gentse kweker Louis Van Houtte; een van de meest geplante heesters van de negentiende eeuw." },

{ id:"spiraea-x-billardii", g:"Spiraea", s:"× billardii", nl:"Basterdspirea",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"1,5–2 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"Juli–september", bloeikleur:"Karmijnroze, lange pluim",
  groeivorm:"Heester", groei:"Snel", gebruik:["Landschap","Massief","Oever"],
  onderscheid:"Kruising van <i>douglasii</i> en <i>salicifolia</i>: <b>lange smalle karmijnroze pluimen</b> die langer doorbloeien dan beide ouders. Woekert met uitlopers.",
  weetje:"Veel aangeplant in naoorlogse openbare beplanting; herken je aan hele velden van gelijke struiken." },

{ id:"spiraea-chamaedryfolia", g:"Spiraea", s:"chamaedryfolia", nl:"Gamanderspirea",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"1–1,5 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Wit, halfbolvormig",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Landschap","Massief","Border"],
  onderscheid:"<b>Eirond blad met grove tanden alleen in de bovenste helft</b> en een gave onderste helft. Kantige, zigzaggende twijgen.",
  weetje:"Vormt uitlopers en gedraagt zich meer als een struweelvormer dan als een nette solitair." },

/* ══════════ CORNUS — kornoelje ══════════ */
{ id:"cornus-alba", g:"Cornus", s:"alba", nl:"Witte kornoelje",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Wit, vlak scherm",
  groeivorm:"Heester", groei:"Snel", gebruik:["Winterinteresse","Massief","Oever"],
  onderscheid:"<b>Felrode wintertwijgen</b> en <b>witte bessen</b>. Groeit als een nette horst zonder uitlopers — dat scheidt hem van <i>C. sericea</i>.",
  weetje:"Hoe jonger de twijg, hoe feller het rood: elke twee à drie jaar in maart hard afzetten." },

{ id:"cornus-sanguinea", g:"Cornus", s:"sanguinea", nl:"Rode kornoelje",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–4 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Crèmewit, vlak scherm",
  groeivorm:"Heester", groei:"Snel", gebruik:["Landschap","Haag","Vogelbosje"],
  onderscheid:"De <b>inheemse</b> soort: twijgen dofrood tot groenrood in plaats van fel, en de bessen zijn <b>zwart</b>, niet wit.",
  weetje:"Standaard in landschappelijke hagen. De zwarte bessen zijn voor mensen oneetbaar maar voor vogels topvoedsel." },

{ id:"cornus-mas", g:"Cornus", s:"mas", nl:"Gele kornoelje",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"4–6 m", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"Februari–maart", bloeikleur:"Geel, op kale takken",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Haag","Voorjaarsbloei","Eetbaar"],
  onderscheid:"<b>Gele bloemschermpjes in februari, vóór het blad</b> — de enige gele kornoelje die zo vroeg is. Daarna langwerpige, <b>eetbare rode vruchten</b>.",
  weetje:"De kornoeljes worden verwerkt tot confituur en likeur. Het hout is zo hard dat het in water zinkt." },

{ id:"cornus-kousa", g:"Cornus", s:"kousa", nl:"Japanse kornoelje",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"4–7 m", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"Juni", bloeikleur:"Wit, vier spitse schutbladen",
  groeivorm:"Boom", groei:"Traag", gebruik:["Solitair","Kleine tuin","Herfstkleur"],
  onderscheid:"<b>Vier grote, spits toelopende witte schutbladen</b> in juni, <b>ná</b> het blad. De vrucht is een roze bol als een aardbei.",
  weetje:"Die aardbeivruchten zijn eetbaar en zoet. Bloeit een maand later dan <i>C. florida</i> en is hier veel betrouwbaarder." },

{ id:"cornus-florida", g:"Cornus", s:"florida", nl:"Amerikaanse kornoelje",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"3–6 m", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Wit tot roze, vier brede schutbladen",
  groeivorm:"Boom", groei:"Traag", gebruik:["Solitair","Kleine tuin","Herfstkleur"],
  onderscheid:"Schutbladen <b>breed en met een duidelijke inkeping aan de top</b>, niet spits zoals bij <i>kousa</i>. Bloeit vroeger, vóór of met het blad.",
  weetje:"In Europa gevoelig voor meeldauw en late vorst; <i>C. kousa</i> is hier meestal de betere keuze." },

{ id:"cornus-sericea", g:"Cornus", s:"sericea", nl:"Amerikaanse rode kornoelje",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"2–3 m", breedte:"3–4 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Wit, vlak scherm",
  groeivorm:"Heester", groei:"Snel", gebruik:["Oever","Massief","Winterinteresse","Talud"],
  onderscheid:"Lijkt sterk op <i>C. alba</i>, maar <b>vormt worteluitlopers</b> en groeit daardoor veel breder uit dan hoog. Twijgen rood of geel.",
  weetje:"Die uitlopers maken hem ideaal om een talud of oever vast te leggen, en ongeschikt voor een krappe border." },

{ id:"cornus-controversa", g:"Cornus", s:"controversa", nl:"Reuzenkornoelje",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"8–12 m", breedte:"6–10 m",
  blad:"Bladverliezend", bloeitijd:"Juni", bloeikleur:"Crèmewit, breed scherm",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Solitair","Park","Architecturaal"],
  onderscheid:"<b>Blad staat verspreid</b> in plaats van tegenover elkaar — samen met <i>alternifolia</i> de enige uitzondering. Takken in strakke <b>horizontale etages</b>.",
  weetje:"De etagebouw levert hem de bijnaam bruidstaartboom op; plant hem waar je er van bovenaf op kijkt." },

{ id:"cornus-canadensis", g:"Cornus", s:"canadensis", nl:"Kruidkornoelje",
  standplaats:"Halfschaduw tot schaduw", water:"Normaal tot vochtig", hoogte:"0,15–0,2 m", breedte:"0,4–0,8 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Wit, vier schutbladen",
  groeivorm:"Bodembedekker", groei:"Traag", gebruik:["Bodembedekker","Schaduwtuin","Zure grond"],
  onderscheid:"<b>Geen struik maar een lage vaste plant</b>: kransen van vier tot zes blaadjes met daarboven één bloem met witte schutbladen, en later rode bessen.",
  weetje:"Wil zure, humusrijke, koele grond; slaagt vooral in rododendrongrond en teleurstelt op kalk." },

{ id:"cornus-officinalis", g:"Cornus", s:"officinalis", nl:"Japanse gele kornoelje",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"4–7 m", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"Februari–maart", bloeikleur:"Geel, op kale takken",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Voorjaarsbloei","Winterinteresse"],
  onderscheid:"Lijkt op <i>C. mas</i>, maar de <b>schors schilfert in grillige oranjebruine platen af</b> en de bloemschermen zijn duidelijk groter.",
  weetje:"Die afschilferende stam is zijn troef: in de winter zichtbaar zodra je de onderste takken opkroont." },

{ id:"cornus-alternifolia", g:"Cornus", s:"alternifolia", nl:"Pagodekornoelje",
  standplaats:"Halfschaduw", water:"Normaal", hoogte:"3–5 m", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Crèmewit scherm",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Kleine tuin","Architecturaal"],
  onderscheid:"Ook <b>verspreid blad</b> zoals <i>controversa</i>, maar blijft <b>struikvormig en veel kleiner</b>, met etages die dichter op elkaar staan.",
  weetje:"De bonte vorm <i>'Argentea'</i> is een van de mooiste kleine solitairen voor halfschaduw." },

/* ══════════ ILEX — hulst ══════════ */
{ id:"ilex-aquifolium", g:"Ilex", s:"aquifolium", nl:"Gewone hulst",
  standplaats:"Zon tot schaduw", water:"Normaal", hoogte:"3–10 m", breedte:"2–4 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Wit, klein",
  groeivorm:"Heester", groei:"Traag", gebruik:["Haag","Solitair","Vormsnoei","Vogelbosje"],
  onderscheid:"<b>Sterk gegolfd, leerachtig blad met grote scherpe stekels</b>. Hoger in de plant worden de bladeren vaak gaafrandig — daar hoeft geen vee bij te komen.",
  weetje:"In België een beschermde soort: je mag hem in het wild niet plukken of rooien." },

{ id:"ilex-crenata", g:"Ilex", s:"crenata", nl:"Japanse hulst",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"1–2,5 m", breedte:"1–1,5 m",
  blad:"Bladhoudend", bloeitijd:"Juni", bloeikleur:"Onopvallend wit",
  groeivorm:"Heester", groei:"Traag", gebruik:["Lage haag","Vormsnoei","Buxusvervanger","Pot"],
  onderscheid:"<b>Klein, stomp, gekarteld blad zonder stekels</b> en <b>zwarte</b> bessen. Lijkt op buxus, maar het blad staat <b>verspreid</b> in plaats van tegenover elkaar.",
  weetje:"Dé buxusvervanger sinds de buxusmot. Let op: hij wil zure grond en verdraagt kalk veel slechter dan buxus." },

{ id:"ilex-x-meserveae", g:"Ilex", s:"× meserveae", nl:"Blauwe hulst",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"1,5–2 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Wit tot lichtroze",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Haag","Solitair","Bessendracht"],
  onderscheid:"<b>Blauwgroene glans op het blad</b> en <b>purperkleurige twijgen</b>. Stekelig als <i>aquifolium</i>, maar de kleurzweem verraadt hem.",
  weetje:"Gekweekt door Kathleen Meserve in haar tuin in New York; veel winterharder dan de gewone hulst." },

{ id:"ilex-verticillata", g:"Ilex", s:"verticillata", nl:"Winterbes",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"1,5–3 m", breedte:"1,5–2,5 m",
  blad:"Bladverliezend", bloeitijd:"Juni–juli", bloeikleur:"Onopvallend wit",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Winterinteresse","Snijtak","Oever","Vogelbosje"],
  onderscheid:"<b>De enige hulst die zijn blad verliest.</b> In de winter staan de kale takken helemaal volgepakt met knalrode bessen.",
  weetje:"Wordt massaal geteeld als snijtak voor kerststukken. Wil zure, vochtige grond en verdraagt natte voeten." },

{ id:"ilex-x-altaclerensis", g:"Ilex", s:"× altaclerensis", nl:"Grootbladige hulst",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"4–8 m", breedte:"3–5 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Wit",
  groeivorm:"Heester", groei:"Snel", gebruik:["Haag","Solitair","Windsingel"],
  onderscheid:"<b>Groter en breder blad met weinig of geen stekels</b>, vlakker dan bij <i>aquifolium</i>. Groeit duidelijk forser en sneller.",
  weetje:"Verdraagt zeewind en stadslucht beter dan de gewone hulst; klassiek in kusttuinen." },

{ id:"ilex-cornuta", g:"Ilex", s:"cornuta", nl:"Chinese hulst",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"2–2,5 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Onopvallend geelwit",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Haag","Pot"],
  onderscheid:"<b>Blad bijna rechthoekig, met een stekel op elke hoek en een naar beneden gebogen punt</b> — als een klein schildje. Grote, glanzend rode bessen.",
  weetje:"Zet bessen zonder mannelijke plant in de buurt; een uitzondering binnen het geslacht." },

{ id:"ilex-glabra", g:"Ilex", s:"glabra", nl:"Inktbes",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"1–2 m", breedte:"1–2 m",
  blad:"Bladhoudend", bloeitijd:"Juni", bloeikleur:"Onopvallend wit",
  groeivorm:"Heester", groei:"Traag", gebruik:["Lage haag","Massief","Buxusvervanger"],
  onderscheid:"<b>Smal, gaafrandig, glanzend blad zonder enige stekel of tand</b> en <b>zwarte</b> bessen. Vormt uitlopers en groeit breed uit.",
  weetje:"Verdraagt natte en zure grond beter dan <i>I. crenata</i>; een goede keuze op veengrond." },

{ id:"ilex-pernyi", g:"Ilex", s:"pernyi", nl:"Perny's hulst",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–4 m", breedte:"1,5–2 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Onopvallend geelwit",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Smalle haag","Pot"],
  onderscheid:"<b>Klein, bijna driehoekig blad dat dicht tegen de twijg aanzit</b>, met enkele forse stekels. Smalle, stijf opgaande groeivorm.",
  weetje:"Door die smalle opgaande vorm bruikbaar op plekken waar geen ruimte is voor een brede hulst." },

{ id:"ilex-serrata", g:"Ilex", s:"serrata", nl:"Japanse winterbes",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Juni", bloeikleur:"Onopvallend lichtroze",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Winterinteresse","Snijtak","Solitair"],
  onderscheid:"Ook bladverliezend zoals <i>verticillata</i>, maar met <b>kleiner, fijner gezaagd blad en duidelijk kleinere bessen</b>, in dichtere trosjes.",
  weetje:"In Japan geliefd voor bonsai en snijwerk; de bessen blijven tot ver in de winter zitten." },

{ id:"ilex-opaca", g:"Ilex", s:"opaca", nl:"Amerikaanse hulst",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"5–10 m", breedte:"3–5 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Wit",
  groeivorm:"Boom", groei:"Traag", gebruik:["Solitair","Windsingel","Park"],
  onderscheid:"<b>Blad mat in plaats van glanzend</b>, geelgroen en vlak, met stekels langs de rand. Dat doffe oppervlak is het kenmerk.",
  weetje:"De kersthulst van de Verenigde Staten; groeit uit tot een echte piramidale boom." },

/* ══════════ MAGNOLIA ══════════ */
{ id:"magnolia-stellata", g:"Magnolia", s:"stellata", nl:"Stermagnolia",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"2,5–3 m", breedte:"2,5–3 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Wit, stervormig",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Kleine tuin"],
  onderscheid:"<b>Veel smalle, lintvormige tepalen</b> die als een ster openstaan, op een <b>struikvormige, laag vertakte</b> plant. De kleinste magnolia.",
  weetje:"Bloeit als eerste van het geslacht, en juist daardoor lopen de knoppen risico bij late nachtvorst." },

{ id:"magnolia-x-soulangeana", g:"Magnolia", s:"× soulangeana", nl:"Tulpmagnolia",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"5–8 m", breedte:"4–6 m",
  blad:"Bladverliezend", bloeitijd:"April", bloeikleur:"Buiten roodpaars, binnen wit",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Solitair","Voortuin","Park"],
  onderscheid:"<b>Grote, tulpvormige bloemen die half gesloten blijven</b>, roodpaars aan de buitenkant en wit vanbinnen. De klassieke voortuinmagnolia.",
  weetje:"Kruising van <i>denudata</i> en <i>liliiflora</i>, gemaakt bij Parijs rond 1820 en sindsdien nooit meer weggeweest." },

{ id:"magnolia-grandiflora", g:"Magnolia", s:"grandiflora", nl:"Grootbloemige magnolia",
  standplaats:"Volle zon", water:"Normaal", hoogte:"6–12 m", breedte:"4–7 m",
  blad:"Bladhoudend", bloeitijd:"Juni–september", bloeikleur:"Romig wit, zeer groot",
  groeivorm:"Boom", groei:"Traag", gebruik:["Solitair","Tegen een muur","Kusttuin"],
  onderscheid:"<b>De enige wintergroene</b>: groot, dik, glanzend leerachtig blad met een <b>roestbruine viltlaag aan de onderkant</b>. Bloemen tot 25 cm, sterk geurend.",
  weetje:"Bloeit pas in de zomer en dan wekenlang, telkens enkele bloemen tegelijk. In Vlaanderen het best tegen een warme muur." },

{ id:"magnolia-kobus", g:"Magnolia", s:"kobus", nl:"Beverboom",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"8–12 m", breedte:"5–8 m",
  blad:"Bladverliezend", bloeitijd:"April", bloeikleur:"Wit, zes tepalen",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Laanboom","Park","Solitair"],
  onderscheid:"Wordt een <b>echte boom</b> met een rechte stam, en de bloem heeft <b>zes tepalen</b> — duidelijk minder dan de stermagnolia.",
  weetje:"Bloeit pas rijk als hij een jaar of tien oud is; wie geduld heeft krijgt een boom die decennia meegaat." },

{ id:"magnolia-liliiflora", g:"Magnolia", s:"liliiflora", nl:"Lelie-magnolia",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"2,5–4 m", breedte:"2,5–3,5 m",
  blad:"Bladverliezend", bloeitijd:"April–juni", bloeikleur:"Purperrood buiten, wit binnen",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Kleine tuin","Border"],
  onderscheid:"<b>Struikvormig en laag blijvend</b>, met <b>smalle purperrode bloemen die nooit helemaal opengaan</b> en die tot in juni blijven doorkomen.",
  weetje:"Bloeit later dan de andere en ontsnapt daardoor meestal aan de late vorst — een veilige keuze in koude tuinen." },

{ id:"magnolia-sieboldii", g:"Magnolia", s:"sieboldii", nl:"Zomermagnolia",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"3–5 m", breedte:"3–4 m",
  blad:"Bladverliezend", bloeitijd:"Juni–juli", bloeikleur:"Wit met karmijnrood hart",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Schaduwtuin","Geurtuin"],
  onderscheid:"Bloeit <b>in de zomer, ná het blad</b>: knikkende witte schotelbloemen met een <b>ring felrode meeldraden</b> in het midden.",
  weetje:"Je moet eronder gaan staan om in de bloem te kunnen kijken; plant hem daarom op een talud of langs een pad." },

{ id:"magnolia-wilsonii", g:"Magnolia", s:"wilsonii", nl:"Wilsons magnolia",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"3–5 m", breedte:"3–4 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Wit met rood hart, hangend",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Schaduwtuin","Geurtuin"],
  onderscheid:"Lijkt op <i>sieboldii</i>, maar de bloemen <b>hangen duidelijk naar beneden</b> in plaats van te knikken, en het blad is smaller en langer.",
  weetje:"Wil beschut en koel staan; in volle zon verbrandt het blad en valt de bloei tegen." },

{ id:"magnolia-denudata", g:"Magnolia", s:"denudata", nl:"Yulan-magnolia",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"6–10 m", breedte:"5–8 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Zuiver wit, geurend",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Solitair","Park","Voortuin"],
  onderscheid:"<b>Zuiver witte, breed bekervormige geurende bloemen</b> zonder enig roze, vóór het blad. Wordt met de jaren een brede boom.",
  weetje:"In China al meer dan duizend jaar in tempeltuinen geplant als symbool van zuiverheid." },

{ id:"magnolia-x-loebneri", g:"Magnolia", s:"× loebneri", nl:"Loebners magnolia",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"4–8 m", breedte:"4–6 m",
  blad:"Bladverliezend", bloeitijd:"April", bloeikleur:"Wit tot lichtroze, stervormig",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Solitair","Kleine tuin","Laanboom"],
  onderscheid:"<b>Als een grotere stermagnolia</b>: stervormig met veel tepalen, maar breder en steviger, en hij groeit uit tot een kleine boom.",
  weetje:"Kruising van <i>kobus</i> en <i>stellata</i>: de bloei van de ster met de groeikracht en winterhardheid van de beverboom." },

{ id:"magnolia-tripetala", g:"Magnolia", s:"tripetala", nl:"Parasolmagnolia",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"6–10 m", breedte:"5–8 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Romig wit, groot",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Solitair","Park","Architecturaal"],
  onderscheid:"<b>Reusachtig blad tot een halve meter lang</b>, in schijnkransen aan het uiteinde van elke tak, als een parasol. Onmiskenbaar.",
  weetje:"De grote witte bloemen ruiken uitgesproken onaangenaam; plant hem niet vlak bij een terras." },
/* ══════════ PINUS — den ══════════ */
{ id:"pinus-sylvestris", g:"Pinus", s:"sylvestris", nl:"Grove den",
  standplaats:"Volle zon", water:"Droog", hoogte:"15–25 m", breedte:"6–10 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Geelrood, onopvallend",
  groeivorm:"Conifeer", groei:"Snel", gebruik:["Landschap","Park","Bosbouw","Solitair"],
  onderscheid:"<b>Twee naalden per bundel</b>, kort (4–7 cm), gedraaid en blauwgroen. En vooral: de <b>oranjerode, papierachtig afschilferende schors</b> in de kroon.",
  weetje:"De enige inheemse den. Die oranje bovenstam licht bij avondzon op — het herkenningsteken op de Kempense heide." },

{ id:"pinus-nigra", g:"Pinus", s:"nigra", nl:"Zwarte den",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"20–30 m", breedte:"8–12 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Geel, onopvallend",
  groeivorm:"Conifeer", groei:"Normaal", gebruik:["Windsingel","Kustbeplanting","Park"],
  onderscheid:"<b>Twee naalden per bundel</b>, maar <b>lang (8–15 cm), stijf, recht en donkergroen</b> in plaats van kort en gedraaid. Schors donkergrijs tot zwart.",
  weetje:"Verdraagt zout, wind en stadslucht uitstekend; de standaard windsingel aan de kust." },

{ id:"pinus-mugo", g:"Pinus", s:"mugo", nl:"Bergden",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"1–3 m", breedte:"2–4 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Geel, onopvallend",
  groeivorm:"Conifeer", groei:"Traag", gebruik:["Rotstuin","Pot","Bodembedekker","Talud"],
  onderscheid:"<b>Struikvormig en breed uitgroeiend in plaats van een boom</b>, met twee korte donkergroene naalden per bundel. De enige echte dwergden.",
  weetje:"Groeit van nature op rotsige berghellingen; daardoor extreem wind- en vorstbestendig." },

{ id:"pinus-strobus", g:"Pinus", s:"strobus", nl:"Weymouthden",
  standplaats:"Volle zon", water:"Normaal", hoogte:"20–30 m", breedte:"8–12 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Snel", gebruik:["Park","Windsingel","Solitair"],
  onderscheid:"<b>Vijf naalden per bundel</b>, dun, zacht en blauwgroen — de zachtste den om vast te pakken. Lange, gekromde, harsige kegels.",
  weetje:"Tel de naalden: vijf staat voor de witte dennen, en dat zijn er maar enkele. Gevoelig voor blaasroest." },

{ id:"pinus-pinea", g:"Pinus", s:"pinea", nl:"Parasolden / pijnboom",
  standplaats:"Volle zon", water:"Droog", hoogte:"10–20 m", breedte:"8–12 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Normaal", gebruik:["Solitair","Pot","Mediterrane tuin"],
  onderscheid:"<b>Brede, platte parasolkroon op een kale stam</b> — het silhouet van Toscane. Twee stijve naalden per bundel, en dikke ronde kegels.",
  weetje:"Levert de pijnboompitten uit de keuken. Hier maar beperkt winterhard en meestal als kuipplant verkocht." },

{ id:"pinus-cembra", g:"Pinus", s:"cembra", nl:"Alpenden / arve",
  standplaats:"Volle zon", water:"Normaal", hoogte:"8–15 m", breedte:"3–5 m",
  blad:"Bladhoudend", bloeitijd:"Juni", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Traag", gebruik:["Solitair","Smalle tuin","Rotstuin"],
  onderscheid:"<b>Vijf naalden per bundel</b> zoals de weymouthden, maar <b>dicht, smal en kegelvormig van bouw</b> en veel trager. Blijft tot onderaan betakt.",
  weetje:"Wordt in de Alpen honderden jaren oud. Het geurige hout is het klassieke materiaal voor Tiroler kamers." },

{ id:"pinus-parviflora", g:"Pinus", s:"parviflora", nl:"Japanse witte den",
  standplaats:"Volle zon", water:"Normaal", hoogte:"5–10 m", breedte:"4–8 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Traag", gebruik:["Solitair","Japanse tuin","Bonsai","Pot"],
  onderscheid:"<b>Vijf korte, gedraaide blauwgrijze naalden per bundel</b> en een <b>onregelmatige, gelaagde kroon</b>. Veel kleiner en grilliger dan de weymouthden.",
  weetje:"De bonsai-den bij uitstek; ook in de volle grond blijft hij klein genoeg voor een gewone tuin." },

{ id:"pinus-wallichiana", g:"Pinus", s:"wallichiana", nl:"Tranenden",
  standplaats:"Volle zon", water:"Normaal", hoogte:"15–25 m", breedte:"8–12 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Snel", gebruik:["Park","Solitair","Grote tuin"],
  onderscheid:"<b>Vijf zeer lange (15–20 cm), slappe, afhangende blauwgroene naalden</b> per bundel. De naalden hangen als tranen naar beneden.",
  weetje:"De kegels worden tot 30 cm lang en druipen van de hars; ze hangen als kaarsen aan de takken." },

{ id:"pinus-heldreichii", g:"Pinus", s:"heldreichii", nl:"Slangenhuidden",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"8–15 m", breedte:"4–6 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Traag", gebruik:["Solitair","Park","Droge tuin"],
  onderscheid:"<b>Schors in grijswitte, veelhoekige platen als een slangenhuid</b>, en twee stijve, kaarsrecht afstaande donkergroene naalden per bundel.",
  weetje:"De jonge kegels zijn diep kobaltblauw voor ze verhouten — een van de mooiste kegels van alle dennen." },

{ id:"pinus-contorta", g:"Pinus", s:"contorta", nl:"Draaiden",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"10–20 m", breedte:"5–8 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Snel", gebruik:["Windsingel","Kustbeplanting","Landschap"],
  onderscheid:"<b>Twee korte, sterk gedraaide, gelig groene naalden</b> per bundel, en <b>kleine kegels die scheef en asymmetrisch</b> aan de tak blijven zitten.",
  weetje:"Die kegels gaan in hun natuurlijke gebied pas open na bosbrand; de hars smelt dan en geeft het zaad vrij." },

/* ══════════ JUNIPERUS — jeneverbes ══════════ */
{ id:"juniperus-communis", g:"Juniperus", s:"communis", nl:"Gewone jeneverbes",
  standplaats:"Volle zon", water:"Droog", hoogte:"1–5 m", breedte:"1–3 m",
  blad:"Bladhoudend", bloeitijd:"April–mei", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Traag", gebruik:["Heidetuin","Solitair","Landschap"],
  onderscheid:"<b>Alleen stekelige naaldvormige blaadjes in kransen van drie</b>, nooit schubvormig, met <b>één witte band</b> over de bovenzijde van elke naald.",
  weetje:"De enige inheemse. De bessen rijpen pas in hun derde jaar en zijn de specerij voor jenever en wildgerechten." },

{ id:"juniperus-horizontalis", g:"Juniperus", s:"horizontalis", nl:"Kruipende jeneverbes",
  standplaats:"Volle zon", water:"Droog", hoogte:"0,2–0,4 m", breedte:"1,5–2,5 m",
  blad:"Bladhoudend", bloeitijd:"April–mei", bloeikleur:"Onopvallend",
  groeivorm:"Bodembedekker", groei:"Normaal", gebruik:["Bodembedekker","Talud","Rotstuin","Daktuin"],
  onderscheid:"<b>Volledig plat over de grond kruipend</b>, met fijn schubvormig blauwgroen blad. De platste jeneverbes; hij gaat nooit omhoog.",
  weetje:"Veel vormen verkleuren in de winter paarsbruin; dat is normale seizoenskleur en geen schade." },

{ id:"juniperus-sabina", g:"Juniperus", s:"sabina", nl:"Zevenboom",
  standplaats:"Volle zon", water:"Droog", hoogte:"0,5–1,5 m", breedte:"2–4 m",
  blad:"Bladhoudend", bloeitijd:"April", bloeikleur:"Onopvallend",
  groeivorm:"Bodembedekker", groei:"Snel", gebruik:["Talud","Bodembedekker","Openbaar groen"],
  onderscheid:"Breed uitgroeiend met <b>schuin opgaande takuiteinden</b>. Wrijf het blad: het ruikt <b>scherp en onaangenaam</b>, heel anders dan de andere soorten.",
  weetje:"Sterk giftig, en waardplant voor perenroest. Niet planten bij kinderen, vee of fruitbomen." },

{ id:"juniperus-squamata", g:"Juniperus", s:"squamata", nl:"Schubjeneverbes",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"0,5–2 m", breedte:"1,5–2,5 m",
  blad:"Bladhoudend", bloeitijd:"April–mei", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Traag", gebruik:["Rotstuin","Solitair","Border","Pot"],
  onderscheid:"<b>Intens staalblauw, kort en dicht naaldblad</b> op knikkende takuiteinden. De blauwste jeneverbes; de takpunten hangen typisch iets over.",
  weetje:"De cultivar <i>'Blue Star'</i> is wereldwijd de meest verkochte dwergconifeer." },

{ id:"juniperus-chinensis", g:"Juniperus", s:"chinensis", nl:"Chinese jeneverbes",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"2–8 m", breedte:"1,5–4 m",
  blad:"Bladhoudend", bloeitijd:"April", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Normaal", gebruik:["Solitair","Haag","Vormsnoei","Bonsai"],
  onderscheid:"Draagt <b>beide bladvormen tegelijk</b>: stekelige jeugdnaalden én schubblad op dezelfde plant, vaak op dezelfde tak. Opgaande, kegelvormige bouw.",
  weetje:"De klassieke boom voor Japanse vormsnoei en bonsai; hij verdraagt zeer intensief knippen." },

{ id:"juniperus-x-pfitzeriana", g:"Juniperus", s:"× pfitzeriana", nl:"Pfitzer-jeneverbes",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"1–2 m", breedte:"2–4 m",
  blad:"Bladhoudend", bloeitijd:"April", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Snel", gebruik:["Massief","Talud","Openbaar groen"],
  onderscheid:"<b>Schuin opstijgende takken in een brede, vaasvormige waaier</b>, breder dan hoog. De meest geplante vorm in naoorlogse tuinen.",
  weetje:"Wordt altijd veel breder dan mensen inschatten; reken op minstens drie meter doorsnede." },

{ id:"juniperus-virginiana", g:"Juniperus", s:"virginiana", nl:"Virginische jeneverbes",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"8–15 m", breedte:"3–5 m",
  blad:"Bladhoudend", bloeitijd:"April", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Normaal", gebruik:["Windsingel","Solitair","Haag"],
  onderscheid:"<b>Groeit uit tot een echte smalle boom</b>, met fijn schubblad en <b>afschilferende, roodbruine vezelige schors</b>. De grootste van het geslacht.",
  weetje:"Het geurige hout is de klassieke grondstof voor potloden en voor kleerkasten tegen motten." },

{ id:"juniperus-procumbens", g:"Juniperus", s:"procumbens", nl:"Japanse kruipjeneverbes",
  standplaats:"Volle zon", water:"Droog", hoogte:"0,2–0,3 m", breedte:"1,5–2 m",
  blad:"Bladhoudend", bloeitijd:"April", bloeikleur:"Onopvallend",
  groeivorm:"Bodembedekker", groei:"Traag", gebruik:["Rotstuin","Bodembedekker","Pot","Bonsai"],
  onderscheid:"Kruipend zoals <i>horizontalis</i>, maar met <b>stijve, stekelige naalden</b> in plaats van zacht schubblad, en stijvere, dikkere takken.",
  weetje:"Wordt veel gebruikt voor cascade-bonsai omdat de takken zich natuurlijk over een rand laten hangen." },

{ id:"juniperus-conferta", g:"Juniperus", s:"conferta", nl:"Kustjeneverbes",
  standplaats:"Volle zon", water:"Droog", hoogte:"0,2–0,3 m", breedte:"1,5–2 m",
  blad:"Bladhoudend", bloeitijd:"April–mei", bloeikleur:"Onopvallend",
  groeivorm:"Bodembedekker", groei:"Normaal", gebruik:["Kusttuin","Bodembedekker","Zandgrond","Daktuin"],
  onderscheid:"Kruipend met <b>zachte, frisgroene naalden met een brede witte band</b> — veel lichter van kleur dan de andere kruipers, en niet prikkend.",
  weetje:"Groeit van nature op Japanse zeeduinen en verdraagt zout en stuifzand als geen andere. Botanisch tegenwoordig <i>J. rigida subsp. conferta</i>." },

{ id:"juniperus-scopulorum", g:"Juniperus", s:"scopulorum", nl:"Rotsjeneverbes",
  standplaats:"Volle zon", water:"Droog", hoogte:"4–8 m", breedte:"1–2 m",
  blad:"Bladhoudend", bloeitijd:"April", bloeikleur:"Onopvallend",
  groeivorm:"Conifeer", groei:"Traag", gebruik:["Zuilvorm","Accent","Droge tuin"],
  onderscheid:"<b>Smalle, strak zuilvormige bouw</b> met zilverblauw schubblad. Veel smaller dan <i>virginiana</i> en duidelijk blauwer.",
  weetje:"De cultivar <i>'Skyrocket'</i> wordt hoog en amper een halve meter breed; een cipressilhouet dat hier wél winterhard is." },

/* ══════════ GERANIUM — ooievaarsbek ══════════ */
{ id:"geranium-macrorrhizum", g:"Geranium", s:"macrorrhizum", nl:"Rotsooievaarsbek",
  standplaats:"Halfschaduw tot schaduw", water:"Droog tot normaal", hoogte:"30–40 cm", breedte:"50–60 cm",
  blad:"Halfbladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Roze",
  groeivorm:"Bodembedekker", groei:"Snel", gebruik:["Bodembedekker","Droge schaduw","Onder bomen"],
  onderscheid:"<b>Dik, sterk aromatisch blad</b> dat bij wrijven doordringend ruikt, op <b>vlezige bovengrondse wortelstokken</b>. De enige die droge schaduw echt aankan.",
  weetje:"Uit het blad wordt nog altijd geraniumolie voor parfum gewonnen. Blad verkleurt rood in de herfst." },

{ id:"geranium-sanguineum", g:"Geranium", s:"sanguineum", nl:"Bloedooievaarsbek",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"20–30 cm", breedte:"40–60 cm",
  blad:"Bladverliezend", bloeitijd:"Juni–augustus", bloeikleur:"Karmijnroze",
  groeivorm:"Vaste plant", groei:"Normaal", gebruik:["Rotstuin","Border","Randbeplanting","Droge tuin"],
  onderscheid:"<b>Zeer fijn, diep handvormig ingesneden blad</b> op een lage, dichte kussenvorm, met <b>felle karmijnroze bloemen die er los boven zweven</b>.",
  weetje:"Verdraagt volle zon en droogte beter dan bijna elke andere ooievaarsbek; de herfstkleur is bloedrood." },

{ id:"geranium-x-cantabrigiense", g:"Geranium", s:"× cantabrigiense", nl:"Cambridge-ooievaarsbek",
  standplaats:"Zon tot halfschaduw", water:"Droog tot normaal", hoogte:"20–30 cm", breedte:"40–60 cm",
  blad:"Halfbladhoudend", bloeitijd:"Mei–juli", bloeikleur:"Roze tot wit",
  groeivorm:"Bodembedekker", groei:"Snel", gebruik:["Bodembedekker","Randbeplanting","Talud"],
  onderscheid:"Kruising van <i>macrorrhizum</i> en <i>dalmaticum</i>: <b>lager en compacter dan macrorrhizum</b>, met kleiner, glanzender blad dat ook aromatisch is.",
  weetje:"Sluit sneller dicht dan zijn ouders en blijft netter; daarom de bodembedekker van dienst in openbaar groen." },

{ id:"geranium-pratense", g:"Geranium", s:"pratense", nl:"Beemdooievaarsbek",
  standplaats:"Volle zon", water:"Normaal", hoogte:"60–90 cm", breedte:"50–70 cm",
  blad:"Bladverliezend", bloeitijd:"Juni–augustus", bloeikleur:"Violetblauw",
  groeivorm:"Vaste plant", groei:"Normaal", gebruik:["Border","Bloemenweide","Landschap"],
  onderscheid:"<b>De hoogste van het geslacht</b>, met grote, diep ingesneden bladeren en <b>violetblauwe bloemen</b> op lange stelen. Inheems in wegbermen.",
  weetje:"Na de bloei helemaal terugknippen: binnen enkele weken staat er vers blad en volgt vaak een tweede bloei." },

{ id:"geranium-phaeum", g:"Geranium", s:"phaeum", nl:"Donkere ooievaarsbek",
  standplaats:"Halfschaduw tot schaduw", water:"Normaal", hoogte:"50–70 cm", breedte:"40–50 cm",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Zeer donker paarsbruin",
  groeivorm:"Vaste plant", groei:"Normaal", gebruik:["Schaduwborder","Onder bomen","Natuurlijke tuin"],
  onderscheid:"<b>Bijna zwartpaarse bloempjes met teruggeslagen kroonbladen</b> — er is geen andere ooievaarsbek met zo'n donkere kleur. Vaak een donkere vlek op het blad.",
  weetje:"Wordt ook rouwviooltje genoemd. Bloeit in volle schaduw waar bijna niets anders het doet." },

{ id:"geranium-endressii", g:"Geranium", s:"endressii", nl:"Berkenooievaarsbek",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"40–50 cm", breedte:"50–60 cm",
  blad:"Halfbladhoudend", bloeitijd:"Juni–september", bloeikleur:"Zalmroze",
  groeivorm:"Bodembedekker", groei:"Snel", gebruik:["Border","Bodembedekker","Massief"],
  onderscheid:"<b>Heldere zalmroze bloemen met fijne donkere adertjes</b>, maandenlang achter elkaar, boven frisgroen, licht glanzend blad.",
  weetje:"Bloeit van juni tot de vorst als je hem halverwege de zomer eenmaal terugknipt." },

{ id:"geranium-himalayense", g:"Geranium", s:"himalayense", nl:"Himalaya-ooievaarsbek",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"30–45 cm", breedte:"50–70 cm",
  blad:"Bladverliezend", bloeitijd:"Juni–juli", bloeikleur:"Diep violetblauw, grote bloem",
  groeivorm:"Vaste plant", groei:"Normaal", gebruik:["Border","Bodembedekker","Massief"],
  onderscheid:"<b>De grootste bloem van het geslacht</b>, tot 5 cm, diep violetblauw met een rode weerschijn in het hart. Lager en breder dan <i>pratense</i>.",
  weetje:"De beroemde cultivar <i>'Rozanne'</i> stamt hiervan af en bloeit van juni tot november door." },

{ id:"geranium-renardii", g:"Geranium", s:"renardii", nl:"Fluweelooievaarsbek",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"25–30 cm", breedte:"30–40 cm",
  blad:"Bladverliezend", bloeitijd:"Juni", bloeikleur:"Wit met paarse adering",
  groeivorm:"Vaste plant", groei:"Traag", gebruik:["Rotstuin","Randbeplanting","Droge tuin"],
  onderscheid:"<b>Grijsgroen, dik gerimpeld en fluweelachtig blad</b> dat het hele seizoen mooi blijft, met witte bloemen vol <b>fijne paarse aderlijnen</b>.",
  weetje:"Wordt vooral om het blad geplant: die grijze fluwelen rozet is decoratiever dan de vrij korte bloei." },

{ id:"geranium-nodosum", g:"Geranium", s:"nodosum", nl:"Knoopooievaarsbek",
  standplaats:"Halfschaduw tot schaduw", water:"Normaal", hoogte:"30–45 cm", breedte:"40–50 cm",
  blad:"Bladverliezend", bloeitijd:"Mei–september", bloeikleur:"Lila met donkere aders",
  groeivorm:"Bodembedekker", groei:"Snel", gebruik:["Schaduwborder","Onder bomen","Bodembedekker"],
  onderscheid:"<b>Glanzend, ondiep drie- tot vijflobbig blad</b> — veel minder diep ingesneden dan bij de andere soorten — en duidelijk <b>gezwollen stengelknopen</b>.",
  weetje:"Zaait zich vriendelijk uit in schaduw en vult vanzelf gaten op; een van de weinige die daar maandenlang doorbloeit." },

{ id:"geranium-sylvaticum", g:"Geranium", s:"sylvaticum", nl:"Bosooievaarsbek",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"50–70 cm", breedte:"40–50 cm",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Blauwviolet met wit hart",
  groeivorm:"Vaste plant", groei:"Normaal", gebruik:["Schaduwborder","Bosrand","Natuurlijke tuin"],
  onderscheid:"Lijkt op <i>pratense</i> maar <b>bloeit een maand vroeger, blijft lager en heeft een duidelijk wit hart</b> in de bloem. Rechtopstaande vruchtstelen.",
  weetje:"Bloeit al in mei, wanneer de meeste vaste planten nog moeten beginnen; ideaal onder bladverliezende bomen." },

/* ══════════ CLEMATIS — bosrank ══════════ */
{ id:"clematis-montana", g:"Clematis", s:"montana", nl:"Bergbosrank",
  standplaats:"Volle zon", water:"Normaal tot vochtig", hoogte:"6–10 m", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Wit tot roze, viertallig",
  groeivorm:"Klimplant", groei:"Snel", gebruik:["Pergola","Grote muur","Door een oude boom"],
  onderscheid:"<b>Massale bloei in mei op oud hout</b>, met kleine viertallige bloemen over de hele plant. Drietallig blad. De sterkst groeiende van allemaal.",
  weetje:"Snoeigroep 1: alleen meteen na de bloei bijknippen. Snoei je in het voorjaar, dan bloeit hij dat jaar niet." },

{ id:"clematis-viticella", g:"Clematis", s:"viticella", nl:"Italiaanse bosrank",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"3–4 m", breedte:"1–2 m",
  blad:"Bladverliezend", bloeitijd:"Juli–september", bloeikleur:"Purper tot violet, knikkend",
  groeivorm:"Klimplant", groei:"Snel", gebruik:["Pergola","Door een heester","Muurbegroeiing"],
  onderscheid:"<b>Kleine, knikkende klokvormige bloemen in de zomer</b>, op hout van dat jaar. Fijn geveerd blad; de plant blijft luchtig en licht.",
  weetje:"Snoeigroep 3: in maart terug tot 30 cm. Veruit de minst gevoelige soort voor clematisverwelkingsziekte." },

{ id:"clematis-armandii", g:"Clematis", s:"armandii", nl:"Wintergroene bosrank",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"4–6 m", breedte:"2–3 m",
  blad:"Bladhoudend", bloeitijd:"Maart–april", bloeikleur:"Wit, sterk geurend",
  groeivorm:"Klimplant", groei:"Snel", gebruik:["Groen scherm","Beschutte muur","Geurtuin"],
  onderscheid:"<b>De enige wintergroene</b>: groot, leerachtig, glanzend drietallig blad dat het hele jaar blijft. Geurende witte bloemen zeer vroeg in het voorjaar.",
  weetje:"Wil beschut tegen een warme muur; bij strenge vorst verbrandt het blad, al loopt hij meestal weer uit." },

{ id:"clematis-alpina", g:"Clematis", s:"alpina", nl:"Alpenbosrank",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"1–1,5 m",
  blad:"Bladverliezend", bloeitijd:"April–mei", bloeikleur:"Blauwviolet, knikkende klokjes",
  groeivorm:"Klimplant", groei:"Normaal", gebruik:["Kleine tuin","Noordmuur","Pergola","Pot"],
  onderscheid:"<b>Knikkende, enkelvoudige klokjes met vier tepalen</b> in april, op een kleine, fijne plant. Verdraagt als een van de weinige een koude noordmuur.",
  weetje:"Snoeigroep 1, en eigenlijk hoef je hem nooit te snoeien. Daarna volgen decoratieve zilveren zaadpluizen." },

{ id:"clematis-macropetala", g:"Clematis", s:"macropetala", nl:"Bosrank met gevulde klokjes",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"1–1,5 m",
  blad:"Bladverliezend", bloeitijd:"April–mei", bloeikleur:"Blauw, ogenschijnlijk gevuld",
  groeivorm:"Klimplant", groei:"Normaal", gebruik:["Kleine tuin","Pergola","Pot","Noordmuur"],
  onderscheid:"Lijkt op <i>alpina</i>, maar de klokjes ogen <b>gevuld</b>: er zitten extra gekleurde blaadjes binnenin de bloem, als een kleine rok.",
  weetje:"Die extra blaadjes zijn omgevormde meeldraden. Even winterhard en onverwoestbaar als de alpenbosrank." },

{ id:"clematis-tangutica", g:"Clematis", s:"tangutica", nl:"Gele bosrank",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"3–5 m", breedte:"1,5–2,5 m",
  blad:"Bladverliezend", bloeitijd:"Juli–oktober", bloeikleur:"Helder geel, lampionvormig",
  groeivorm:"Klimplant", groei:"Snel", gebruik:["Pergola","Hek","Droge tuin"],
  onderscheid:"<b>De enige met gele bloemen</b>: knikkende lampionnetjes van dik, bijna wasachtig materiaal, van juli tot in de herfst.",
  weetje:"Bloemen en zilveren zaadpluizen hangen wekenlang samen in de plant; hij verdraagt droogte uitstekend." },

{ id:"clematis-flammula", g:"Clematis", s:"flammula", nl:"Geurende bosrank",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"3–5 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Augustus–oktober", bloeikleur:"Wit, wolkig, sterk geurend",
  groeivorm:"Klimplant", groei:"Snel", gebruik:["Pergola","Geurtuin","Hek"],
  onderscheid:"<b>Wolken van heel kleine witte stervormige bloempjes</b> in de nazomer, met een <b>doordringende amandel- of honinggeur</b>. Fijn, blauwgroen blad.",
  weetje:"Bloeit als vrijwel alle klimplanten uitgebloeid zijn, en de geur draagt op een windstille avond metersver." },

{ id:"clematis-recta", g:"Clematis", s:"recta", nl:"Rechte bosrank",
  standplaats:"Volle zon", water:"Normaal", hoogte:"1–1,5 m", breedte:"0,8–1,2 m",
  blad:"Bladverliezend", bloeitijd:"Juni–juli", bloeikleur:"Romig wit, geurend",
  groeivorm:"Vaste plant", groei:"Normaal", gebruik:["Border","Prairietuin","Geurtuin"],
  onderscheid:"<b>Klimt niet</b>: een rechtopstaande vaste plant die elk jaar tot de grond terugsterft, met geurende witte bloemschermen bovenaan.",
  weetje:"Heeft wel steun nodig, anders gaat hij liggen. Bewijst dat niet elke clematis een klimplant is." },

{ id:"clematis-integrifolia", g:"Clematis", s:"integrifolia", nl:"Blauwe bosrank",
  standplaats:"Volle zon", water:"Normaal", hoogte:"0,5–0,8 m", breedte:"0,5–0,8 m",
  blad:"Bladverliezend", bloeitijd:"Juni–augustus", bloeikleur:"Blauw, knikkend klokje",
  groeivorm:"Vaste plant", groei:"Normaal", gebruik:["Border","Randbeplanting","Snijbloem"],
  onderscheid:"Ook <b>geen klimplant</b>, en bovendien met <b>enkelvoudig, gaafrandig blad</b> — uniek binnen het geslacht, dat verder altijd samengesteld blad heeft.",
  weetje:"De knikkende blauwe klokjes hebben teruggekrulde punten; laat hem door lage vaste planten heen zakken." },

{ id:"clematis-cirrhosa", g:"Clematis", s:"cirrhosa", nl:"Winterbosrank",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"2,5–4 m", breedte:"1,5–2,5 m",
  blad:"Bladhoudend", bloeitijd:"December–maart", bloeikleur:"Crème, vaak rood gespikkeld",
  groeivorm:"Klimplant", groei:"Normaal", gebruik:["Beschutte muur","Winterbloei","Pot"],
  onderscheid:"<b>Bloeit midden in de winter</b>, met knikkende crèmekleurige klokjes die vanbinnen vaak roodbruin gespikkeld zijn. Fijn wintergroen blad.",
  weetje:"Gaat in de zomer in rust en laat dan blad vallen — dat is normaal, geen droogteschade." },

/* ══════════ CAREX — zegge ══════════ */
{ id:"carex-oshimensis", g:"Carex", s:"oshimensis", nl:"Japanse zegge",
  standplaats:"Halfschaduw", water:"Normaal", hoogte:"30–40 cm", breedte:"40–50 cm",
  blad:"Bladhoudend", bloeitijd:"April–mei", bloeikleur:"Bruine aartjes, onopvallend",
  groeivorm:"Siergras", groei:"Normaal", gebruik:["Border","Pot","Bodembedekker","Schaduwtuin"],
  onderscheid:"<b>Sierlijk overhangende, smalle bladeren in een fonteinvorm</b>, wintergroen en vaak bont gestreept. De meest verkochte siersgezegge.",
  weetje:"De cultivar <i>'Evergold'</i> met gele middenstreep staat in half Vlaanderen. Niet afknippen: alleen uitkammen in maart." },

{ id:"carex-morrowii", g:"Carex", s:"morrowii", nl:"Morrows zegge",
  standplaats:"Halfschaduw tot schaduw", water:"Normaal", hoogte:"30–40 cm", breedte:"40–50 cm",
  blad:"Bladhoudend", bloeitijd:"April–mei", bloeikleur:"Bruine aartjes",
  groeivorm:"Siergras", groei:"Normaal", gebruik:["Schaduwborder","Bodembedekker","Onder bomen"],
  onderscheid:"<b>Breder, stijver en leerachtiger blad</b> dan <i>oshimensis</i>, met een duidelijk opstaande in plaats van overhangende pol.",
  weetje:"Verdraagt diepere schaduw dan de meeste zeggen en blijft ook in de winter netjes groen." },

{ id:"carex-pendula", g:"Carex", s:"pendula", nl:"Hangende zegge",
  standplaats:"Halfschaduw tot schaduw", water:"Normaal tot vochtig", hoogte:"1–1,5 m", breedte:"1–1,5 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Lange hangende bruine aren",
  groeivorm:"Siergras", groei:"Snel", gebruik:["Oever","Schaduwtuin","Natuurlijke tuin"],
  onderscheid:"<b>Veruit de grootste</b>, tot anderhalve meter, met <b>lange, sierlijk overhangende bloemaren</b> als kattenstaarten aan gebogen stelen.",
  weetje:"Inheems in vochtige bossen. Zaait zich royaal uit; op een kleine tuin wordt dat snel te veel." },

{ id:"carex-buchananii", g:"Carex", s:"buchananii", nl:"Bronzen zegge",
  standplaats:"Volle zon", water:"Normaal", hoogte:"50–70 cm", breedte:"30–40 cm",
  blad:"Bladhoudend", bloeitijd:"Juni", bloeikleur:"Onopvallend bruin",
  groeivorm:"Siergras", groei:"Normaal", gebruik:["Border","Pot","Accent","Prairietuin"],
  onderscheid:"<b>Stijf rechtopstaande, koperbruine bladeren met gekrulde puntjes</b> — de plant lijkt het hele jaar dood, maar dat is zijn natuurlijke kleur.",
  weetje:"De meest gestelde vraag bij deze plant is of hij dood is. Nee: die bronskleur hoort erbij, ook in volle groei." },

{ id:"carex-testacea", g:"Carex", s:"testacea", nl:"Oranje zegge",
  standplaats:"Volle zon", water:"Normaal", hoogte:"40–60 cm", breedte:"40–60 cm",
  blad:"Bladhoudend", bloeitijd:"Juni", bloeikleur:"Onopvallend",
  groeivorm:"Siergras", groei:"Normaal", gebruik:["Border","Pot","Accent","Kusttuin"],
  onderscheid:"<b>Olijfgroen blad dat naar de punten toe oranjebruin verkleurt</b>, in een overhangende fontein. Kleurt feller naarmate hij meer zon krijgt.",
  weetje:"In volle zon en op schrale grond kleurt hij koperoranje; in de schaduw blijft hij dof groen." },

{ id:"carex-muskingumensis", g:"Carex", s:"muskingumensis", nl:"Palmzegge",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"50–70 cm", breedte:"40–60 cm",
  blad:"Bladverliezend", bloeitijd:"Juni–juli", bloeikleur:"Groenbruine aartjes",
  groeivorm:"Siergras", groei:"Snel", gebruik:["Oever","Schaduwborder","Massief"],
  onderscheid:"<b>Bladeren in kransen rond rechtopstaande stengels, als kleine palmpjes of papyrus</b>. Geen enkele andere zegge ziet er zo uit.",
  weetje:"De enige uit dit rijtje die zijn blad volledig verliest; in maart mag hij wél kort worden afgeknipt." },

{ id:"carex-flagellifera", g:"Carex", s:"flagellifera", nl:"Zweepzegge",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"40–60 cm", breedte:"50–70 cm",
  blad:"Bladhoudend", bloeitijd:"Juni", bloeikleur:"Onopvallend",
  groeivorm:"Siergras", groei:"Normaal", gebruik:["Border","Pot","Bodembedekker"],
  onderscheid:"Roodbruin zoals <i>buchananii</i>, maar <b>overhangend en los in plaats van stijf rechtop</b>, met zeer dunne, zweepachtige slierten.",
  weetje:"Komt uit Nieuw-Zeeland, net als de andere bronskleurige zeggen; die kleur is daar een aanpassing aan fel licht." },

{ id:"carex-elata", g:"Carex", s:"elata", nl:"Stijve zegge",
  standplaats:"Zon tot halfschaduw", water:"Vochtig", hoogte:"50–80 cm", breedte:"50–70 cm",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Zwartbruine aren",
  groeivorm:"Siergras", groei:"Normaal", gebruik:["Oever","Vijverrand","Moerastuin"],
  onderscheid:"<b>Stijf rechtopstaande pol op een verhoogde voet</b> die met de jaren een echte bult vormt. Inheems in moerassen en langs oevers.",
  weetje:"De gele cultivar <i>'Aurea'</i> is een van de weinige felgele planten die in de vijverrand gedijen." },

{ id:"carex-comans", g:"Carex", s:"comans", nl:"Haarzegge",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"30–40 cm", breedte:"40–50 cm",
  blad:"Bladhoudend", bloeitijd:"Juni", bloeikleur:"Onopvallend",
  groeivorm:"Siergras", groei:"Normaal", gebruik:["Border","Pot","Randbeplanting"],
  onderscheid:"<b>Extreem fijn, haardun blad</b> dat als een pruik alle kanten op valt. Bestaat in een groene en een bronzen vorm.",
  weetje:"Zo fijn dat de pol van een afstand op een bos haar lijkt; combineert goed met grofbladige planten." },

{ id:"carex-grayi", g:"Carex", s:"grayi", nl:"Morgensterzegge",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"50–70 cm", breedte:"40–50 cm",
  blad:"Bladverliezend", bloeitijd:"Juni–juli", bloeikleur:"Groene stekelbollen",
  groeivorm:"Siergras", groei:"Normaal", gebruik:["Oever","Border","Droogboeket"],
  onderscheid:"<b>Bolvormige, stekelige vruchthoofdjes als kleine morgensterren</b> aan de stengeltoppen — geen enkele andere zegge heeft die.",
  weetje:"Die stekelbollen blijven maandenlang zitten en worden graag gebruikt in droogboeketten." },

];
