/* PlantenTrainer — de soorten binnen de tien geslachten.

   Het veld "onderscheid" is het belangrijkste: dat is waaraan je déze soort
   herkent tussen zijn soortgenoten. Familie staat niet per soort vermeld,
   want die volgt uit het geslacht (zie geslachtdata.js).

   Vaste woordenschat, gelijk aan data.js:
     standplaats : Volle zon | Zon tot halfschaduw | Halfschaduw |
                   Halfschaduw tot schaduw | Zon tot schaduw | Schaduw
     water       : Droog | Droog tot normaal | Normaal | Normaal tot vochtig | Vochtig
     blad        : Bladverliezend | Bladhoudend | Halfbladhoudend
     groeivorm   : Boom | Heester | Vaste plant | Siergras | Klimplant | Conifeer |
                   Bodembedekker | Bolgewas
*/

const SOORTDATA = [

/* ══════════ ACER — esdoorn ══════════ */
{ id:"acer-palmatum", g:"Acer", s:"palmatum", nl:"Japanse esdoorn",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"4–6 m", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"April–mei", bloeikleur:"Onopvallend roodbruin",
  groeivorm:"Boom", groei:"Traag", gebruik:["Solitair","Pot","Japanse tuin"],
  onderscheid:"Klein blad van 4 tot 7 cm met 5 tot 7 <b>diep ingesneden, spitse</b> lobben. Fijne, gelaagde vertakking. Veel kleiner en fijner dan alle andere esdoorns hier.",
  weetje:"Wil beschut staan: ochtendzon na nachtvorst en droge wind verbranden het jonge blad." },

{ id:"acer-platanoides", g:"Acer", s:"platanoides", nl:"Noorse esdoorn",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"20–30 m", breedte:"12–18 m",
  blad:"Bladverliezend", bloeitijd:"April", bloeikleur:"Geelgroen, vóór het blad",
  groeivorm:"Boom", groei:"Snel", gebruik:["Laanboom","Park","Solitair"],
  onderscheid:"Blad breder dan lang met <b>lang toegespitste, draadvormige punten</b>. Breek de bladsteel af: er komt <b>melksap</b> uit. Dat is hét verschil met de gewone esdoorn.",
  weetje:"Bloeit opvallend geelgroen vóór het blad uitloopt — in april kleurt een hele laan er geel van." },

{ id:"acer-pseudoplatanus", g:"Acer", s:"pseudoplatanus", nl:"Gewone esdoorn",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"20–30 m", breedte:"12–20 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Groengeel, hangende trossen",
  groeivorm:"Boom", groei:"Snel", gebruik:["Laanboom","Windsingel","Park"],
  onderscheid:"Blad met <b>stompe, grof gezaagde</b> lobben en een <b>rode bladsteel</b> zonder melksap. Bloeit in hangende trossen ná het blad. Schors schilfert bij ouderdom in platen af.",
  weetje:"Zaait zich massaal uit; in bossen geldt hij als lastige indringer. Verdraagt wel zeewind als geen ander." },

{ id:"acer-campestre", g:"Acer", s:"campestre", nl:"Veldesdoorn / Spaanse aak",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"8–15 m", breedte:"6–10 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Geelgroen",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Haag","Laanboom","Landschap"],
  onderscheid:"<b>Klein blad met afgeronde, stompe lobben</b> — het minst 'esdoornachtige' blad van allemaal. Melksap in de bladsteel. Twijgen krijgen vaak <b>kurklijsten</b>.",
  weetje:"De enige inheemse esdoorn die zich als haag laat scheren; klassiek in landschappelijke beplanting." },

{ id:"acer-rubrum", g:"Acer", s:"rubrum", nl:"Rode esdoorn",
  standplaats:"Volle zon", water:"Normaal tot vochtig", hoogte:"12–18 m", breedte:"8–12 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Rood, vóór het blad",
  groeivorm:"Boom", groei:"Snel", gebruik:["Laanboom","Solitair","Park"],
  onderscheid:"Blad met <b>3 tot 5 lobben en een witachtige onderkant</b>, veel kleiner dan bij de Noorse esdoorn. <b>Rode</b> bloemen, rode bladstelen, rode herfstkleur — alles is rood.",
  weetje:"Verdraagt natte grond beter dan de meeste bomen; in Noord-Amerika groeit hij in moerassen." },

{ id:"acer-saccharinum", g:"Acer", s:"saccharinum", nl:"Zilveresdoorn",
  standplaats:"Volle zon", water:"Normaal tot vochtig", hoogte:"20–25 m", breedte:"12–18 m",
  blad:"Bladverliezend", bloeitijd:"Maart", bloeikleur:"Groenrood, zeer vroeg",
  groeivorm:"Boom", groei:"Snel", gebruik:["Park","Grote tuin","Solitair"],
  onderscheid:"<b>Diep ingesneden blad met een zilverwitte onderkant</b> dat bij de minste wind omklapt — vandaar de naam. De diepste insnijdingen van alle grote esdoorns.",
  weetje:"Groeit zeer snel maar maakt brak hout; takbreuk bij storm is een bekend probleem in stedelijk groen." },

{ id:"acer-griseum", g:"Acer", s:"griseum", nl:"Papieresdoorn",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"6–10 m", breedte:"4–6 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Groengeel, onopvallend",
  groeivorm:"Boom", groei:"Traag", gebruik:["Solitair","Kleine tuin","Winterinteresse"],
  onderscheid:"De enige esdoorn hier met <b>drietallig samengesteld blad</b> (drie aparte blaadjes). En die schors: <b>kaneelbruin en afschilferend in flinterdunne vellen</b>.",
  weetje:"Wordt vooral om de schors geplant — in de winter licht die oranjebruin op tegen de lucht." },

{ id:"acer-japonicum", g:"Acer", s:"japonicum", nl:"Japanse waaieresdoorn",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"4–8 m", breedte:"3–6 m",
  blad:"Bladverliezend", bloeitijd:"April–mei", bloeikleur:"Purperrood, hangend",
  groeivorm:"Boom", groei:"Traag", gebruik:["Solitair","Japanse tuin","Beschutte plek"],
  onderscheid:"Blad <b>rond als een waaier met 9 tot 11 ondiepe lobben</b> — duidelijk ronder en met méér lobben dan <i>A. palmatum</i>. Jong blad is zijdeachtig behaard.",
  weetje:"Bloeit opvallender dan de meeste esdoorns: purperrode bloemen die onder het jonge blad uit hangen." },

{ id:"acer-negundo", g:"Acer", s:"negundo", nl:"Vederesdoorn",
  standplaats:"Volle zon", water:"Normaal", hoogte:"10–15 m", breedte:"8–12 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Groen, hangende kwastjes",
  groeivorm:"Boom", groei:"Snel", gebruik:["Park","Pionierbeplanting"],
  onderscheid:"<b>Geveerd samengesteld blad met 3 tot 7 blaadjes</b> — lijkt in niets op een esdoorn, meer op een vlier. Alleen de tegenoverstaande stand en de helikoptertjes verraden het geslacht. Twijgen vaak <b>berijpt blauwgroen</b>.",
  weetje:"Klassieke instinker op een examen: iedereen denkt aan een vlier tot hij de vruchten ziet." },

{ id:"acer-davidii", g:"Acer", s:"davidii", nl:"Slangenbastesdoorn",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"8–12 m", breedte:"5–8 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Geelgroen, hangende trossen",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Solitair","Kleine tuin","Winterinteresse"],
  onderscheid:"<b>Ongelobd, eivormig blad</b> — de enige esdoorn hier zonder lobben. Schors <b>groen met witte lengtestrepen</b>, als een slangenhuid.",
  weetje:"Die gestreepte schors blijft tot op hoge leeftijd; plant hem waar je er in de winter langs loopt." },

/* ══════════ BUXUS — palmboompje ══════════ */
{ id:"buxus-sempervirens", g:"Buxus", s:"sempervirens", nl:"Gewone buxus",
  standplaats:"Zon tot schaduw", water:"Normaal", hoogte:"1–5 m", breedte:"1–2 m",
  blad:"Bladhoudend", bloeitijd:"Maart–april", bloeikleur:"Onopvallend geelgroen",
  groeivorm:"Heester", groei:"Traag", gebruik:["Vormsnoei","Lage haag","Pot"],
  onderscheid:"Blad <b>ovaal, 1,5 tot 3 cm, met een licht ingedeukte top</b> en donkergroen glanzend. De grootste bladeren van het geslacht; wordt ook het hoogst.",
  weetje:"De enige buxus die echt boomvormig kan worden — in Zuid-Europa staan exemplaren van acht meter." },

{ id:"buxus-microphylla", g:"Buxus", s:"microphylla", nl:"Kleinbladige buxus",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"0,6–1,5 m", breedte:"0,6–1,2 m",
  blad:"Bladhoudend", bloeitijd:"Maart–april", bloeikleur:"Onopvallend geelgroen",
  groeivorm:"Heester", groei:"Traag", gebruik:["Lage haag","Vormsnoei","Randbeplanting"],
  onderscheid:"<b>Duidelijk kleiner blad</b> dan de gewone buxus, tot 1,5 cm, smaller en lichter groen. Blijft veel lager en compacter.",
  weetje:"Verdraagt vorst en zon beter dan <i>B. sempervirens</i>; daarom vaak gekozen op winderige plekken." },

{ id:"buxus-harlandii", g:"Buxus", s:"harlandii", nl:"Harlands buxus",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"0,5–1 m", breedte:"0,5–1 m",
  blad:"Bladhoudend", bloeitijd:"April", bloeikleur:"Onopvallend geelgroen",
  groeivorm:"Heester", groei:"Traag", gebruik:["Pot","Bonsai","Vormsnoei"],
  onderscheid:"<b>Smal, langwerpig blad</b> dat naar de voet toe versmalt, frisgroen en glanzend. Open, grillige vertakking in plaats van een dichte bol.",
  weetje:"In de handel vaak verkocht als potplant of vormsnoei; minder winterhard dan de andere buxussoorten." },

{ id:"buxus-balearica", g:"Buxus", s:"balearica", nl:"Balearenbuxus",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"2–5 m", breedte:"1,5–3 m",
  blad:"Bladhoudend", bloeitijd:"Maart–april", bloeikleur:"Geelgroen, geurend",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Droge tuin","Pot"],
  onderscheid:"<b>Het grootste blad van alle buxussoorten</b>, tot 4 cm, leerachtig en dofgroen. Grovere indruk dan alle andere.",
  weetje:"Komt van de Balearen en Zuid-Spanje; verdraagt hitte en droogte, maar is hier maar beperkt winterhard." },

{ id:"buxus-sinica", g:"Buxus", s:"sinica", nl:"Chinese buxus",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"1–2 m", breedte:"1–1,5 m",
  blad:"Bladhoudend", bloeitijd:"Maart–april", bloeikleur:"Onopvallend geelgroen",
  groeivorm:"Heester", groei:"Traag", gebruik:["Lage haag","Vormsnoei","Pot"],
  onderscheid:"Klein, <b>breed omgekeerd eivormig blad</b> met een duidelijk ingedeukte top, vaak met een bronskleurige winterverkleuring.",
  weetje:"De variëteit <i>insularis</i> is de winterhardste buxus die er bestaat en wordt daarom veel gekruist." },

/* ══════════ PRUNUS ══════════ */
{ id:"prunus-laurocerasus", g:"Prunus", s:"laurocerasus", nl:"Laurierkers",
  standplaats:"Zon tot schaduw", water:"Normaal", hoogte:"2–6 m", breedte:"2–4 m",
  blad:"Bladhoudend", bloeitijd:"April–mei", bloeikleur:"Witte rechtopstaande trossen",
  groeivorm:"Heester", groei:"Snel", gebruik:["Haag","Scherm","Massief"],
  onderscheid:"<b>Groot, leerachtig, glanzend wintergroen blad</b> van 10 tot 15 cm. Rechtopstaande witte bloemtrossen. Veruit het grofste blad van het geslacht.",
  weetje:"Geen keukenlaurier — dat is <i>Laurus nobilis</i>. Verwildert via vogels in bossen en verdringt daar de onderbegroeiing." },

{ id:"prunus-lusitanica", g:"Prunus", s:"lusitanica", nl:"Portugese laurierkers",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"3–6 m", breedte:"2–4 m",
  blad:"Bladhoudend", bloeitijd:"Juni", bloeikleur:"Witte hangende trossen",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Haag","Solitair","Pot","Vormsnoei"],
  onderscheid:"Lijkt op laurierkers maar met <b>kleiner, smaller blad en een opvallend rode bladsteel</b>. Bloeit een maand later, in langere hangende trossen.",
  weetje:"Winterhardere en veel nettere vervanger van de laurierkers; verdraagt kalk en droogte beter." },

{ id:"prunus-avium", g:"Prunus", s:"avium", nl:"Zoete kers / boskers",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"15–25 m", breedte:"8–12 m",
  blad:"Bladverliezend", bloeitijd:"April", bloeikleur:"Wit, in schermen",
  groeivorm:"Boom", groei:"Snel", gebruik:["Laanboom","Solitair","Landschap"],
  onderscheid:"Grote <b>boom</b> met hangend, slap neerhangend blad en <b>glanzende roodbruine schors met opvallende horizontale streepjes</b> die in banden loslaat. Eetbare zoete kersen.",
  weetje:"De stamvader van al onze zoete kersenrassen. De herfstkleur is oranjerood en zeer betrouwbaar." },

{ id:"prunus-serrulata", g:"Prunus", s:"serrulata", nl:"Japanse sierkers",
  standplaats:"Volle zon", water:"Normaal", hoogte:"6–10 m", breedte:"4–8 m",
  blad:"Bladverliezend", bloeitijd:"April–mei", bloeikleur:"Roze, vaak gevuld",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Solitair","Laanboom","Kleine tuin"],
  onderscheid:"<b>Zwaar gevulde roze bloemen</b> die als pompons aan de takken hangen, en jong blad dat <b>bronsrood</b> uitloopt. Scherp en dubbel gezaagd blad.",
  weetje:"De hanami-boom uit Japan. Gevulde bloemen zetten geen vrucht en leveren dus niets op voor insecten." },

{ id:"prunus-padus", g:"Prunus", s:"padus", nl:"Vogelkers",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"10–15 m", breedte:"6–10 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Witte hangende pluimen",
  groeivorm:"Boom", groei:"Snel", gebruik:["Landschap","Vogelbosje","Oever"],
  onderscheid:"De enige inheemse Prunus met <b>lange, hangende bloemtrossen</b> in plaats van schermen. Schors ruikt onaangenaam scherp bij het kerven.",
  weetje:"Wordt in het voorjaar vaak volledig ingesponnen door de stippelmot — spectaculair, maar de boom loopt weer uit." },

{ id:"prunus-spinosa", g:"Prunus", s:"spinosa", nl:"Sleedoorn",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"2–4 m", breedte:"2–4 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Wit, vóór het blad",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Haag","Landschap","Vogelbosje"],
  onderscheid:"Doornige struik met <b>echte scherpe doorns</b> en <b>witte bloemen op kale takken</b>, nog vóór het blad. Klein blad, blauwberijpte zwarte vruchtjes.",
  weetje:"De sleepruimpjes worden pas eetbaar na de eerste vorst. Onmisbaar in landschappelijke hagen: doornstruweel is topnestgelegenheid." },

{ id:"prunus-cerasifera", g:"Prunus", s:"cerasifera", nl:"Kerspruim",
  standplaats:"Volle zon", water:"Normaal", hoogte:"6–10 m", breedte:"4–8 m",
  blad:"Bladverliezend", bloeitijd:"Maart", bloeikleur:"Wit tot lichtroze",
  groeivorm:"Boom", groei:"Snel", gebruik:["Kleine tuin","Haag","Straatboom"],
  onderscheid:"<b>De vroegste bloeier van het geslacht</b>, vaak al eind februari, met bloemen op nog kale takken. Geen doorns, in tegenstelling tot de sleedoorn.",
  weetje:"De roodbladige vormen (<i>'Nigra'</i>, <i>'Pissardii'</i>) staan in half Vlaanderen — maar de soort zelf is groenbladig." },

{ id:"prunus-subhirtella", g:"Prunus", s:"subhirtella", nl:"Winterkers",
  standplaats:"Volle zon", water:"Normaal", hoogte:"5–8 m", breedte:"4–6 m",
  blad:"Bladverliezend", bloeitijd:"November–maart", bloeikleur:"Lichtroze",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Solitair","Kleine tuin","Winterbloei"],
  onderscheid:"De enige Prunus die <b>midden in de winter bloeit</b> — bij zacht weer van november tot maart, telkens een handvol bloemen tegelijk. Fijne, ijle kroon.",
  weetje:"Een tak in de vaas bloeit binnen open. Voor bijen op zachte winterdagen soms de enige nectarbron." },

{ id:"prunus-incisa", g:"Prunus", s:"incisa", nl:"Fuji-kers",
  standplaats:"Volle zon", water:"Normaal", hoogte:"3–6 m", breedte:"2–4 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Wit tot lichtroze",
  groeivorm:"Heester", groei:"Traag", gebruik:["Kleine tuin","Pot","Solitair","Bonsai"],
  onderscheid:"<b>Klein, diep en dubbel ingesneden blad</b> en een fijne, dichte vertakking. Blijft struikvormig en klein — de kleinste sierkers.",
  weetje:"Wordt veel als bonsai gebruikt en verdraagt snoei goed, wat zeldzaam is bij Prunus." },

{ id:"prunus-domestica", g:"Prunus", s:"domestica", nl:"Pruim",
  standplaats:"Volle zon", water:"Normaal", hoogte:"4–8 m", breedte:"3–6 m",
  blad:"Bladverliezend", bloeitijd:"April", bloeikleur:"Wit",
  groeivorm:"Boom", groei:"Normaal", gebruik:["Fruitboom","Hoogstam","Boomgaard"],
  onderscheid:"<b>Mat, dik, gerimpeld blad</b> zonder glans, en dikke grijze twijgen. De vrucht is de bekende pruim met een vlakke naad over de lengte.",
  weetje:"Een oude kruising die al duizenden jaren in cultuur is; in het wild bestaat de soort niet." },

/* ══════════ VIBURNUM — sneeuwbal ══════════ */
{ id:"viburnum-tinus", g:"Viburnum", s:"tinus", nl:"Sneeuwbal",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"1,5–2,5 m",
  blad:"Bladhoudend", bloeitijd:"November–april", bloeikleur:"Wit uit roze knop",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Haag","Scherm","Pot","Winterbloei"],
  onderscheid:"<b>Wintergroen, klein donker leerachtig blad</b> en bloei in de winter. De enige Viburnum die van november tot april doorbloeit.",
  weetje:"Matig winterhard: onder −12 °C vriest hij terug. Geef hem een beschutte plek tegen een muur." },

{ id:"viburnum-opulus", g:"Viburnum", s:"opulus", nl:"Gelderse roos",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"2–4 m", breedte:"2–4 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Wit, plat scherm met randbloemen",
  groeivorm:"Heester", groei:"Snel", gebruik:["Landschap","Oever","Vogelbosje","Haag"],
  onderscheid:"<b>Drie- tot vijflobbig blad als een esdoorn</b> — heel ongewoon voor het geslacht. Vlak scherm met grote steriele randbloemen, daarna glanzende rode bessen.",
  weetje:"Inheems. Het viburnumhaantje kan hem in enkele weken kaalvreten; de struik overleeft dat meestal wel." },

{ id:"viburnum-plicatum", g:"Viburnum", s:"plicatum", nl:"Japanse sneeuwbal",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Wit, in etages",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Solitair","Border","Massief"],
  onderscheid:"<b>Horizontaal uitgroeiende takken in duidelijke etages</b>, met de witte schermen als schoteltjes bovenop. Blad diep geplooid met evenwijdige nerven.",
  weetje:"De laagsgewijze bouw is zijn handelsmerk; plant hem waar je er van bovenaf op kijkt." },

{ id:"viburnum-davidii", g:"Viburnum", s:"davidii", nl:"Davids sneeuwbal",
  standplaats:"Halfschaduw tot schaduw", water:"Normaal", hoogte:"0,6–1 m", breedte:"1–1,5 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Wit, klein scherm",
  groeivorm:"Bodembedekker", groei:"Traag", gebruik:["Bodembedekker","Massief","Schaduwborder"],
  onderscheid:"Laag en breed uitgroeiend, met <b>leerachtig blad met drie diep ingezonken lengtenerven</b> — dat nervenpatroon herken je meteen. Metaalblauwe bessen.",
  weetje:"Voor bessen heb je een mannelijke én vrouwelijke plant nodig; plant er dus altijd meerdere." },

{ id:"viburnum-rhytidophyllum", g:"Viburnum", s:"rhytidophyllum", nl:"Rimpelbladige sneeuwbal",
  standplaats:"Halfschaduw", water:"Normaal", hoogte:"3–4 m", breedte:"2,5–3,5 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Geelwit, groot scherm",
  groeivorm:"Heester", groei:"Snel", gebruik:["Scherm","Massief","Solitair"],
  onderscheid:"<b>Lang, smal, sterk gerimpeld wintergroen blad</b> met een viltige grijsbruine onderkant. Het grofste en meest opvallende blad van het geslacht.",
  weetje:"Bij vorst rolt het blad zich strak op als sigaren — een normale reactie, geen schade." },

{ id:"viburnum-carlesii", g:"Viburnum", s:"carlesii", nl:"Geurende sneeuwbal",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"1,5–2 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"April–mei", bloeikleur:"Wit uit roze knop",
  groeivorm:"Heester", groei:"Traag", gebruik:["Border","Bij het terras","Geurtuin"],
  onderscheid:"Compacte struik met <b>dofgroen, viltig behaard blad</b> en halfbolvormige bloemschermen die <b>zeer sterk zoet geuren</b>. De geur is het kenmerk.",
  weetje:"Plant hem bij een deur of terras: de geur draagt op een windstille avond metersver." },

{ id:"viburnum-lantana", g:"Viburnum", s:"lantana", nl:"Wollige sneeuwbal",
  standplaats:"Zon tot halfschaduw", water:"Droog tot normaal", hoogte:"3–4 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Crèmewit, plat scherm",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Landschap","Haag","Kalkgrond"],
  onderscheid:"Blad en twijgen <b>dicht grijsviltig behaard</b>, ruw aanvoelend. <b>Naakte knoppen zonder schubben</b> — uniek binnen het geslacht en een prima winterkenmerk.",
  weetje:"Inheems op kalkgrond. De bessen kleuren eerst rood en dan zwart, vaak in dezelfde tros tegelijk." },

{ id:"viburnum-farreri", g:"Viburnum", s:"farreri", nl:"Winterbloeiende sneeuwbal",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"1,5–2,5 m",
  blad:"Bladverliezend", bloeitijd:"November–maart", bloeikleur:"Roze knop, witte bloem",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Winterbloei","Border","Geurtuin"],
  onderscheid:"Bladverliezend én winterbloeiend: <b>geurende bloemtrosjes op kale takken</b> van november tot maart. Blad met diep ingezonken nerven, bronskleurig bij uitlopen.",
  weetje:"De bloemen verdragen lichte vorst; na een vriesnacht opent de volgende lading gewoon weer." },

{ id:"viburnum-x-burkwoodii", g:"Viburnum", s:"× burkwoodii", nl:"Burkwoods sneeuwbal",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"1,5–2,5 m",
  blad:"Halfbladhoudend", bloeitijd:"April–mei", bloeikleur:"Wit uit roze knop",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Border","Geurtuin","Haag"],
  onderscheid:"Kruising van <i>carlesii</i> en <i>utile</i>: even sterk geurend als <i>carlesii</i>, maar <b>groter, losser en half wintergroen</b>, met glanzender blad.",
  weetje:"Houdt in een zachte winter zijn blad, in een strenge niet — vandaar 'half bladhoudend'." },

{ id:"viburnum-x-bodnantense", g:"Viburnum", s:"× bodnantense", nl:"Bodnant-sneeuwbal",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2,5–3,5 m", breedte:"1,5–2,5 m",
  blad:"Bladverliezend", bloeitijd:"November–maart", bloeikleur:"Donkerroze",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Winterbloei","Geurtuin","Solitair"],
  onderscheid:"Winterbloeier met <b>duidelijk donkerder roze en grotere bloemtrossen</b> dan <i>farreri</i>, op stijf rechtopstaande takken.",
  weetje:"De cultivar <i>'Dawn'</i> is veruit de meest geplante; de geur is zwaar en zoet, midden in december." },

/* ══════════ HYDRANGEA — hortensia ══════════ */
{ id:"hydrangea-macrophylla", g:"Hydrangea", s:"macrophylla", nl:"Boerenhortensia",
  standplaats:"Halfschaduw", water:"Vochtig", hoogte:"1–2 m", breedte:"1–1,5 m",
  blad:"Bladverliezend", bloeitijd:"Juli–september", bloeikleur:"Roze of blauw",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Border","Pot","Beschutte plek"],
  onderscheid:"<b>Groot, dik, glanzend en grof gezaagd blad</b> en bolvormige of platte bloemschermen. Bloemkleur hangt af van de bodem — als enige samen met <i>serrata</i>.",
  weetje:"Bloeit op hout van vorig jaar: in het voorjaar terugknippen kost je de hele bloei. Remonterende cultivars vergeven dat wel." },

{ id:"hydrangea-paniculata", g:"Hydrangea", s:"paniculata", nl:"Pluimhortensia",
  standplaats:"Zon tot halfschaduw", water:"Normaal tot vochtig", hoogte:"2–3 m", breedte:"1,5–2,5 m",
  blad:"Bladverliezend", bloeitijd:"Juli–september", bloeikleur:"Wit, verkleurend naar roze",
  groeivorm:"Heester", groei:"Snel", gebruik:["Border","Solitair","Haag","Snijbloem"],
  onderscheid:"<b>Kegelvormige pluim</b> in plaats van een bol of schotel, en <b>smaller, matter blad</b>. Verdraagt als enige hortensia volle zon.",
  weetje:"Bloeit op nieuw hout: in maart hard terugsnoeien tot twee ogen geeft juist de grootste pluimen." },

{ id:"hydrangea-arborescens", g:"Hydrangea", s:"arborescens", nl:"Sneeuwbalhortensia",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"1–1,5 m", breedte:"1–1,5 m",
  blad:"Bladverliezend", bloeitijd:"Juni–september", bloeikleur:"Crèmewit tot wit",
  groeivorm:"Heester", groei:"Snel", gebruik:["Border","Massief","Schaduwtuin"],
  onderscheid:"<b>Dun, zacht, hartvormig blad met een blauwgroene onderkant</b> en grote bolronde witte schermen op slappe stelen die snel doorhangen.",
  weetje:"Bloeit op nieuw hout en kan elk voorjaar tot de grond terug. De cultivar <i>'Annabelle'</i> is wereldwijd de bekendste hortensia." },

{ id:"hydrangea-quercifolia", g:"Hydrangea", s:"quercifolia", nl:"Eikenbladhortensia",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"1,5–2 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"Juni–augustus", bloeikleur:"Wit, verkleurend naar roze",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Border","Solitair","Herfstkleur"],
  onderscheid:"<b>Diep gelobd blad als van een eik</b> — onmiskenbaar binnen het geslacht. Rechtopstaande pluimen en een diep wijnrode herfstkleur.",
  weetje:"De enige hortensia met echte herfstkleur; de oude schors rolt bovendien kaneelbruin af." },

{ id:"hydrangea-serrata", g:"Hydrangea", s:"serrata", nl:"Berghortensia",
  standplaats:"Halfschaduw", water:"Vochtig", hoogte:"0,8–1,2 m", breedte:"0,8–1,2 m",
  blad:"Bladverliezend", bloeitijd:"Juni–augustus", bloeikleur:"Blauw of roze, plat scherm",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Border","Pot","Kleine tuin"],
  onderscheid:"Als een <b>kleinere, fijnere boerenhortensia</b>: smaller en spitser blad, altijd platte schermen met een krans randbloemen, en compacter.",
  weetje:"Winterhardere knoppen dan <i>macrophylla</i>; bloeit daardoor betrouwbaarder na een strenge winter." },

{ id:"hydrangea-aspera", g:"Hydrangea", s:"aspera", nl:"Fluweelhortensia",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Juli–augustus", bloeikleur:"Lila met witte randbloemen",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Solitair","Grote border","Schaduwtuin"],
  onderscheid:"<b>Groot, langwerpig, ruw en fluweelachtig behaard blad</b> — aaien en je weet het meteen. Grote platte schermen met lila middenbloemen.",
  weetje:"Wordt een forse struik en heeft ruimte nodig; de oude schors schilfert los in dunne repen." },

{ id:"hydrangea-anomala", g:"Hydrangea", s:"anomala", nl:"Klimhortensia",
  standplaats:"Halfschaduw tot schaduw", water:"Normaal tot vochtig", hoogte:"8–12 m klimmend", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"Juni", bloeikleur:"Wit, plat scherm",
  groeivorm:"Klimplant", groei:"Traag", gebruik:["Muurbegroeiing","Noordmuur","Door een boom"],
  onderscheid:"De enige hortensia die <b>klimt met hechtwortels</b>, zoals klimop. Vaak verkocht als <i>H. petiolaris</i>, dat is dezelfde plant.",
  weetje:"Doet er enkele jaren over om aan te slaan en gaat dan pas los; een van de weinige klimmers voor een noordmuur." },

{ id:"hydrangea-involucrata", g:"Hydrangea", s:"involucrata", nl:"Schutbladhortensia",
  standplaats:"Halfschaduw", water:"Vochtig", hoogte:"0,8–1,2 m", breedte:"1–1,5 m",
  blad:"Bladverliezend", bloeitijd:"Augustus–september", bloeikleur:"Lichtblauw tot wit",
  groeivorm:"Heester", groei:"Traag", gebruik:["Border","Schaduwtuin","Pot"],
  onderscheid:"Laag blijvend, met <b>ruw behaard blad</b> en knoppen die in <b>ronde schutbladen als kleine kooltjes</b> verpakt zitten tot ze opengaan.",
  weetje:"Bloeit als laatste van het geslacht, in augustus en september; vriest hier vaak terug maar loopt weer uit." },

{ id:"hydrangea-heteromalla", g:"Hydrangea", s:"heteromalla", nl:"Hemelse hortensia",
  standplaats:"Halfschaduw", water:"Normaal tot vochtig", hoogte:"2–4 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Juni–juli", bloeikleur:"Wit, groot plat scherm",
  groeivorm:"Heester", groei:"Snel", gebruik:["Solitair","Grote border","Landschap"],
  onderscheid:"Forse struik tot boomvormig, met <b>lang spits blad dat witviltig behaard is aan de onderkant</b> en grote vlakke witte schermen. Rode bladstelen.",
  weetje:"De winterhardste hortensia van allemaal; verdraagt moeiteloos −25 °C." },
/* ══════════ COTONEASTER — dwergmispel ══════════ */
{ id:"cotoneaster-horizontalis", g:"Cotoneaster", s:"horizontalis", nl:"Vlakke dwergmispel",
  standplaats:"Zon tot halfschaduw", water:"Droog tot normaal", hoogte:"0,5–1 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Roze, klein",
  groeivorm:"Bodembedekker", groei:"Normaal", gebruik:["Bodembedekker","Tegen een muur","Talud"],
  onderscheid:"<b>Takken in een strak visgraatpatroon</b>, plat tegen de grond of tegen een muur op. Dat patroon herken je van tien meter ver.",
  weetje:"Rode bessen blijven tot diep in de winter hangen; de herfstkleur is vuurrood." },

{ id:"cotoneaster-dammeri", g:"Cotoneaster", s:"dammeri", nl:"Kruipende dwergmispel",
  standplaats:"Zon tot halfschaduw", water:"Droog tot normaal", hoogte:"0,2–0,3 m", breedte:"1,5–2 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Wit",
  groeivorm:"Bodembedekker", groei:"Snel", gebruik:["Bodembedekker","Talud","Openbaar groen"],
  onderscheid:"<b>Volledig plat over de grond kruipend</b> en wintergroen, met kleine glanzende blaadjes. De laagste van het geslacht; wortelt waar de takken de grond raken.",
  weetje:"De standaard bodembedekker in openbaar groen: sluit dicht, verdraagt droogte en vraagt geen onderhoud." },

{ id:"cotoneaster-franchetii", g:"Cotoneaster", s:"franchetii", nl:"Franchets dwergmispel",
  standplaats:"Zon tot halfschaduw", water:"Droog tot normaal", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Halfbladhoudend", bloeitijd:"Juni", bloeikleur:"Roze-wit",
  groeivorm:"Heester", groei:"Snel", gebruik:["Haag","Scherm","Vogelbosje"],
  onderscheid:"Opgaande struik met <b>sierlijk overhangende takken</b> en blad dat <b>grijsviltig behaard is aan de onderkant</b>. Oranjerode bessen.",
  weetje:"Onderzoek wees uit dat deze soort door zijn behaarde blad opvallend veel fijnstof uit de lucht vangt." },

{ id:"cotoneaster-lacteus", g:"Cotoneaster", s:"lacteus", nl:"Melkwitte dwergmispel",
  standplaats:"Zon tot halfschaduw", water:"Droog tot normaal", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Bladhoudend", bloeitijd:"Juni–juli", bloeikleur:"Melkwit, in brede schermen",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Haag","Scherm","Vogelbosje"],
  onderscheid:"<b>Groot, stevig leerachtig wintergroen blad met diep ingezonken nerven</b> en een viltige onderkant. Het grofste blad van het geslacht.",
  weetje:"De bessen blijven tot in maart hangen — vogels beginnen er pas aan als er niets anders meer is." },

{ id:"cotoneaster-salicifolius", g:"Cotoneaster", s:"salicifolius", nl:"Wilgbladige dwergmispel",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–4 m", breedte:"2–3 m",
  blad:"Bladhoudend", bloeitijd:"Juni", bloeikleur:"Wit",
  groeivorm:"Heester", groei:"Snel", gebruik:["Haag","Scherm","Bodembedekker"],
  onderscheid:"<b>Lang, smal wilgachtig blad</b> van 4 tot 8 cm, glanzend en wintergroen, op overhangende takken. Het smalste blad van het geslacht.",
  weetje:"Lage cultivars zoals <i>'Repens'</i> worden als bodembedekker gebruikt; de soort zelf wordt een forse struik." },

{ id:"cotoneaster-divaricatus", g:"Cotoneaster", s:"divaricatus", nl:"Spreidende dwergmispel",
  standplaats:"Zon tot halfschaduw", water:"Droog tot normaal", hoogte:"1,5–2 m", breedte:"1,5–2 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Roze",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Haag","Massief","Herfstkleur"],
  onderscheid:"Opgaand en <b>wijd gespreid vertakt</b>, niet plat zoals <i>horizontalis</i>, met klein glanzend blad en heldere oranjerode herfstkleur.",
  weetje:"Laat zich goed scheren tot een lage haag en is daar duurzamer in dan de meeste dwergmispels." },

{ id:"cotoneaster-integerrimus", g:"Cotoneaster", s:"integerrimus", nl:"Gewone dwergmispel",
  standplaats:"Volle zon", water:"Droog", hoogte:"1–2 m", breedte:"1–1,5 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Roze, knikkend",
  groeivorm:"Heester", groei:"Traag", gebruik:["Rotstuin","Kalkgrond","Landschap"],
  onderscheid:"Kleine struik met <b>rond tot eivormig blad met een grijsviltige onderkant</b> en knikkende roze bloempjes. De enige inheemse soort van het geslacht.",
  weetje:"In België zeldzaam en beschermd; groeit van nature op droge kalkrotsen." },

{ id:"cotoneaster-multiflorus", g:"Cotoneaster", s:"multiflorus", nl:"Veelbloemige dwergmispel",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"2–4 m", breedte:"2–4 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Wit, overvloedig",
  groeivorm:"Heester", groei:"Snel", gebruik:["Solitair","Vogelbosje","Landschap"],
  onderscheid:"<b>Uitbundig witte bloei</b> die de hele struik bedekt, op lange overhangende takken. Bloeit veruit het opvallendst van het geslacht.",
  weetje:"In bloei lijkt hij op een kleine sierkers; de bessen zijn daarna knalrood en talrijk." },

{ id:"cotoneaster-bullatus", g:"Cotoneaster", s:"bullatus", nl:"Blaasjesdwergmispel",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Juni", bloeikleur:"Roze",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Solitair","Massief","Herfstkleur"],
  onderscheid:"<b>Sterk gebobbeld, blaasachtig gerimpeld blad</b> met diep ingezonken nerven — de naam zegt het. Grote hangende bestrossen.",
  weetje:"Herfstkleur diep oranjerood; blad en bessen blijven lang samen aan de struik hangen." },

/* ══════════ EUONYMUS — kardinaalsmuts ══════════ */
{ id:"euonymus-europaeus", g:"Euonymus", s:"europaeus", nl:"Wilde kardinaalsmuts",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–5 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Onopvallend groengeel",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Landschap","Haag","Vogelbosje"],
  onderscheid:"Inheemse struik met <b>groene, duidelijk vierkantige twijgen</b> en de klassieke <b>felroze vierlobbige doosvrucht met oranje zaad</b>. Blad smal en spits.",
  weetje:"Het hout is zeer fijn en hard; er werden vroeger spoelen en breinaalden van gedraaid. Alle delen zijn giftig." },

{ id:"euonymus-fortunei", g:"Euonymus", s:"fortunei", nl:"Kruipende kardinaalsmuts",
  standplaats:"Zon tot schaduw", water:"Normaal", hoogte:"0,3–0,6 m of 3 m klimmend", breedte:"1–2 m",
  blad:"Bladhoudend", bloeitijd:"Juni–juli", bloeikleur:"Onopvallend groenwit",
  groeivorm:"Bodembedekker", groei:"Normaal", gebruik:["Bodembedekker","Muurbegroeiing","Pot"],
  onderscheid:"De enige <b>wintergroene, kruipende of klimmende</b> soort van het geslacht. Hecht zich met wortels aan een muur als je hem laat.",
  weetje:"Dezelfde plant gedraagt zich als bodembedekker op de grond en als klimmer tegen een muur — de vorm volgt de plek." },

{ id:"euonymus-alatus", g:"Euonymus", s:"alatus", nl:"Kurkwaardige kardinaalsmuts",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"1,5–2,5 m", breedte:"1,5–2,5 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Onopvallend groengeel",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Herfstkleur","Border"],
  onderscheid:"<b>Echte kurklijsten als vleugels op de twijgen</b>, tot vier per tak — onmiskenbaar, ook in de winter. Herfstkleur fel karmijnrood.",
  weetje:"Wordt in het Engels 'burning bush' genoemd, en terecht: de herfstkleur is de felste van alle heesters hier." },

{ id:"euonymus-japonicus", g:"Euonymus", s:"japonicus", nl:"Japanse kardinaalsmuts",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–4 m", breedte:"1,5–2,5 m",
  blad:"Bladhoudend", bloeitijd:"Juni", bloeikleur:"Onopvallend groenwit",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Haag","Pot","Vormsnoei","Kusttuin"],
  onderscheid:"Opgaande struik met <b>dik, stijf, sterk glanzend wintergroen blad</b> dat bijna kunstmatig oogt. Veel forser en rechter dan <i>fortunei</i>.",
  weetje:"Verdraagt zeewind en stadslucht uitstekend; klassieke haagplant aan de kust." },

{ id:"euonymus-planipes", g:"Euonymus", s:"planipes", nl:"Sachalinkardinaalsmuts",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"3–4 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Groengeel",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Solitair","Herfstkleur","Grote border"],
  onderscheid:"<b>Groot blad tot 12 cm</b> en de <b>grootste vruchten van het geslacht</b>, dieprood en hangend aan lange stelen. Ook de dikste rode knoppen.",
  weetje:"Staat in de handel ook als <i>E. sachalinensis</i>; botanisch is dat dezelfde plant." },

{ id:"euonymus-phellomanus", g:"Euonymus", s:"phellomanus", nl:"Kurktwijgkardinaalsmuts",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Groengeel",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Solitair","Herfstkleur","Border"],
  onderscheid:"Net als <i>alatus</i> met kurklijsten, maar <b>grover, onregelmatiger en op een veel opgaander struik</b>, met groter blad en overvloedig roze vruchten.",
  weetje:"De vruchtdracht is spectaculairder dan bij <i>alatus</i>: hele takken hangen vol roze doosvruchten." },

{ id:"euonymus-hamiltonianus", g:"Euonymus", s:"hamiltonianus", nl:"Hamiltons kardinaalsmuts",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"4–6 m", breedte:"3–4 m",
  blad:"Bladverliezend", bloeitijd:"Juni", bloeikleur:"Groengeel",
  groeivorm:"Heester", groei:"Snel", gebruik:["Solitair","Kleine boom","Landschap"],
  onderscheid:"Groeit uit tot een <b>kleine boom</b>, de grootste van het geslacht, met lang spits blad en roze vruchten. Twijgen rond, zonder kurk of vleugels.",
  weetje:"Wordt in Japan als kleine parkboom gebruikt; hier zie je hem vooral in arboreta." },

{ id:"euonymus-oxyphyllus", g:"Euonymus", s:"oxyphyllus", nl:"Scherpbladige kardinaalsmuts",
  standplaats:"Halfschaduw", water:"Normaal", hoogte:"2–4 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Groenpurper",
  groeivorm:"Heester", groei:"Traag", gebruik:["Solitair","Herfstkleur","Schaduwborder"],
  onderscheid:"<b>Fijn en scherp gezaagd, spits toelopend blad</b> en <b>lang afhangende vruchtstelen</b> waaraan de karmijnrode doosvruchten als lampionnetjes bengelen.",
  weetje:"De herfstkleur is dieppaarsrood, en de vruchten hangen dan nog aan de kale takken." },

{ id:"euonymus-verrucosus", g:"Euonymus", s:"verrucosus", nl:"Wrattige kardinaalsmuts",
  standplaats:"Halfschaduw", water:"Normaal", hoogte:"1,5–3 m", breedte:"1,5–2,5 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Bruinrood gevlekt",
  groeivorm:"Heester", groei:"Traag", gebruik:["Landschap","Schaduwborder","Bosrand"],
  onderscheid:"<b>Twijgen bezaaid met kleine zwarte wratjes</b> — voel er met je vingers over, dat is hét kenmerk. Bloemen bruinrood gevlekt in plaats van groengeel.",
  weetje:"Verdraagt echte schaduw beter dan de andere soorten; groeit van nature in de ondergroei van eikenbossen." },

{ id:"euonymus-latifolius", g:"Euonymus", s:"latifolius", nl:"Breedbladige kardinaalsmuts",
  standplaats:"Halfschaduw", water:"Normaal", hoogte:"3–5 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Groengeel",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Solitair","Herfstkleur","Bosrand"],
  onderscheid:"<b>Breed blad tot 15 cm</b>, het breedste van het geslacht, en <b>grote vijflobbige</b> karmijnrode vruchten in plaats van vierlobbige.",
  weetje:"Die vijfde lob is een betrouwbaar determinatiekenmerk: tel gewoon de ribben van de doosvrucht." },

/* ══════════ SALIX — wilg ══════════ */
{ id:"salix-alba", g:"Salix", s:"alba", nl:"Schietwilg",
  standplaats:"Volle zon", water:"Vochtig", hoogte:"15–25 m", breedte:"10–15 m",
  blad:"Bladverliezend", bloeitijd:"April", bloeikleur:"Geelgroene katjes",
  groeivorm:"Boom", groei:"Snel", gebruik:["Knotwilg","Oever","Landschap","Windsingel"],
  onderscheid:"Grote boom met <b>lang smal blad dat zilverwit behaard is aan de onderkant</b> — een rij schietwilgen in de wind wordt zilvergrijs. De klassieke knotwilg.",
  weetje:"Bevat salicine, de grondstof waaruit aspirine werd ontwikkeld. Knotten elke drie tot zes jaar, anders scheurt de kop uit." },

{ id:"salix-caprea", g:"Salix", s:"caprea", nl:"Boswilg / katwilg",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"5–10 m", breedte:"4–6 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Zilvergrijze katjes, daarna geel",
  groeivorm:"Heester", groei:"Snel", gebruik:["Landschap","Vogelbosje","Bijenplant"],
  onderscheid:"<b>Breed, ovaal, gerimpeld blad</b> in plaats van smal — de enige wilg hier met zulk rond blad. De dikke zilveren katjes zijn de bekende palmkatjes.",
  weetje:"De belangrijkste vroege drachtplant die we hebben: in maart zoemt een bloeiende boswilg van de hommels." },

{ id:"salix-babylonica", g:"Salix", s:"babylonica", nl:"Treurwilg",
  standplaats:"Volle zon", water:"Vochtig", hoogte:"10–15 m", breedte:"10–15 m",
  blad:"Bladverliezend", bloeitijd:"April", bloeikleur:"Groengele katjes",
  groeivorm:"Boom", groei:"Snel", gebruik:["Solitair","Vijverrand","Park"],
  onderscheid:"<b>Tot op de grond neerhangende, zeer lange twijgen</b> — geen enkele andere wilg treurt zo sterk. Blad lang en smal, lichtgroen.",
  weetje:"Wortels zoeken agressief naar water en dringen rioleringen binnen; plant hem nooit dicht bij leidingen." },

{ id:"salix-viminalis", g:"Salix", s:"viminalis", nl:"Katwilg / bindwilg",
  standplaats:"Volle zon", water:"Vochtig", hoogte:"3–6 m", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Gele katjes",
  groeivorm:"Heester", groei:"Snel", gebruik:["Vlechtwerk","Oever","Biomassa","Windsingel"],
  onderscheid:"<b>Zeer lang, lijnvormig blad</b> tot 25 cm, met omgerolde randen en een zilverviltige onderkant. Kaarsrechte, taaie, lange twijgen.",
  weetje:"De wilg van de mandenmakerij en van levende wilgenhutten; hij kan meer dan twee meter per jaar maken." },

{ id:"salix-purpurea", g:"Salix", s:"purpurea", nl:"Bittere wilg",
  standplaats:"Volle zon", water:"Normaal tot vochtig", hoogte:"2–4 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Purperrode katjes",
  groeivorm:"Heester", groei:"Snel", gebruik:["Oever","Vlechtwerk","Landschap"],
  onderscheid:"<b>Purperrode twijgen</b> en, uitzonderlijk voor een wilg, <b>bijna tegenoverstaande bladeren</b>. Blad blauwgroen en smal.",
  weetje:"De bast is uitgesproken bitter, vandaar de naam; wordt gebruikt voor fijn vlechtwerk." },

{ id:"salix-integra", g:"Salix", s:"integra", nl:"Japanse sierwilg",
  standplaats:"Volle zon", water:"Normaal tot vochtig", hoogte:"1,5–3 m", breedte:"1,5–2,5 m",
  blad:"Bladverliezend", bloeitijd:"April", bloeikleur:"Kleine gelige katjes",
  groeivorm:"Heester", groei:"Snel", gebruik:["Solitair","Pot","Stamvorm","Border"],
  onderscheid:"Sierlijke struik met <b>bijna tegenoverstaand, klein blad</b> dat bij de bonte vormen <b>roze, wit en groen gevlekt</b> uitloopt.",
  weetje:"Meestal verkocht als <i>'Hakuro-nishiki'</i> op stam. Elk voorjaar hard terugsnoeien geeft de felste jonge kleuren." },

{ id:"salix-cinerea", g:"Salix", s:"cinerea", nl:"Grauwe wilg",
  standplaats:"Zon tot halfschaduw", water:"Vochtig", hoogte:"3–6 m", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"Maart–april", bloeikleur:"Grijze katjes, daarna geel",
  groeivorm:"Heester", groei:"Snel", gebruik:["Oever","Moeras","Landschap"],
  onderscheid:"Struikvormig met <b>grijsviltig behaarde twijgen en blad</b>. Schraap de bast van een tweejarige twijg: daaronder zitten <b>duidelijke lengterichels</b> in het hout.",
  weetje:"De typische wilg van natte, verruigde terreinen; vormt vaak ondoordringbaar wilgenstruweel." },

{ id:"salix-repens", g:"Salix", s:"repens", nl:"Kruipwilg",
  standplaats:"Volle zon", water:"Normaal tot vochtig", hoogte:"0,3–1 m", breedte:"1–2 m",
  blad:"Bladverliezend", bloeitijd:"April", bloeikleur:"Kleine zilvergrijze katjes",
  groeivorm:"Bodembedekker", groei:"Normaal", gebruik:["Duinbeplanting","Bodembedekker","Heide"],
  onderscheid:"<b>Dwergstruikje dat over de grond kruipt</b>, met klein zijdeachtig behaard blad. De enige wilg hier die laag blijft.",
  weetje:"Inheems in duinen en op vochtige heide; houdt met zijn wortelnet stuivend zand vast." },

{ id:"salix-daphnoides", g:"Salix", s:"daphnoides", nl:"Berijpte wilg",
  standplaats:"Volle zon", water:"Normaal tot vochtig", hoogte:"6–10 m", breedte:"4–6 m",
  blad:"Bladverliezend", bloeitijd:"Maart", bloeikleur:"Grote zilverwitte katjes",
  groeivorm:"Boom", groei:"Snel", gebruik:["Landschap","Bijenplant","Oever"],
  onderscheid:"<b>Twijgen met een blauwwitte, berijpte waslaag</b> die je er met je duim kan afvegen. Onmiskenbaar in de winter.",
  weetje:"Bloeit als een van de eerste wilgen, soms al eind februari; zeer waardevol voor vroege bijen." },

{ id:"salix-triandra", g:"Salix", s:"triandra", nl:"Amandelwilg",
  standplaats:"Volle zon", water:"Vochtig", hoogte:"4–8 m", breedte:"3–5 m",
  blad:"Bladverliezend", bloeitijd:"April–mei", bloeikleur:"Geelwitte katjes",
  groeivorm:"Heester", groei:"Snel", gebruik:["Vlechtwerk","Oever","Landschap"],
  onderscheid:"<b>Schors die in onregelmatige platen afschilfert</b> als bij een plataan — uniek onder onze wilgen. Blad glanzend en amandelvormig.",
  weetje:"De geliefde wilg van de mandenmakers: de tenen zijn taai, glad en laten zich goed schillen." },

/* ══════════ QUERCUS — eik ══════════ */
{ id:"quercus-robur", g:"Quercus", s:"robur", nl:"Zomereik",
  standplaats:"Volle zon", water:"Normaal", hoogte:"20–35 m", breedte:"15–25 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Groengele katjes",
  groeivorm:"Boom", groei:"Traag", gebruik:["Laanboom","Park","Landschap","Solitair"],
  onderscheid:"<b>Blad met een zeer korte steel en twee oorlelletjes aan de voet</b>, plus <b>eikels op een lange steel</b>. Onthoud het omgekeerde: kort blad, lange eikel.",
  weetje:"Onze belangrijkste inheemse boom: meer dan vijfhonderd insectensoorten leven ervan. Wordt makkelijk vijfhonderd jaar." },

{ id:"quercus-petraea", g:"Quercus", s:"petraea", nl:"Wintereik",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"20–30 m", breedte:"15–20 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Groengele katjes",
  groeivorm:"Boom", groei:"Traag", gebruik:["Laanboom","Park","Landschap"],
  onderscheid:"Precies het spiegelbeeld van de zomereik: <b>lange bladsteel zonder oorlelletjes</b> en <b>eikels zonder steel</b>, direct op de twijg.",
  weetje:"Verdraagt drogere en armere grond dan de zomereik en houdt zijn blad regelmatiger in een rechte kroon." },

{ id:"quercus-rubra", g:"Quercus", s:"rubra", nl:"Amerikaanse eik",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"20–25 m", breedte:"15–20 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Geelgroene katjes",
  groeivorm:"Boom", groei:"Snel", gebruik:["Laanboom","Park","Herfstkleur"],
  onderscheid:"<b>Groot blad met spitse, in een stekelpuntje eindigende lobben</b> — geen afgeronde lobben zoals bij onze eiken. Herfstkleur diep wijnrood.",
  weetje:"Groeit veel sneller dan de inheemse eiken, maar zijn blad verteert traag en verzuurt de bodem." },

{ id:"quercus-palustris", g:"Quercus", s:"palustris", nl:"Moeraseik",
  standplaats:"Volle zon", water:"Normaal tot vochtig", hoogte:"15–20 m", breedte:"10–15 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Geelgroene katjes",
  groeivorm:"Boom", groei:"Snel", gebruik:["Laanboom","Straatboom","Park"],
  onderscheid:"<b>Diep ingesneden blad met smalle spitse lobben</b> en een kenmerkende kroon: <b>de onderste takken hangen schuin naar beneden</b>, de bovenste staan omhoog.",
  weetje:"Zeer veel geplant als straatboom omdat hij natte grond en verharding goed verdraagt; herfstkleur scharlakenrood." },

{ id:"quercus-cerris", g:"Quercus", s:"cerris", nl:"Moseik / Turkse eik",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"25–35 m", breedte:"15–20 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Geelgroene katjes",
  groeivorm:"Boom", groei:"Snel", gebruik:["Park","Laanboom","Landschap"],
  onderscheid:"<b>Eikelnapje bedekt met lange, kroezige, mosachtige schubben</b> — daar dankt hij zijn naam aan. Blad ruw en onregelmatig gelobd.",
  weetje:"Verdraagt droogte en stadsklimaat uitstekend en wordt daarom steeds vaker als klimaatboom aangeplant." },

{ id:"quercus-ilex", g:"Quercus", s:"ilex", nl:"Steeneik",
  standplaats:"Volle zon", water:"Droog", hoogte:"10–20 m", breedte:"10–15 m",
  blad:"Bladhoudend", bloeitijd:"Mei–juni", bloeikleur:"Gele katjes",
  groeivorm:"Boom", groei:"Traag", gebruik:["Haag","Vormsnoei","Kusttuin","Solitair"],
  onderscheid:"De enige <b>wintergroene</b> eik hier, met <b>klein leerachtig blad dat bij jonge planten stekelig is als hulst</b> en een grijsviltige onderkant heeft.",
  weetje:"Verdraagt zout en zeewind en laat zich scheren; in Zuid-Europa een klassieke haag- en vormboom." },

{ id:"quercus-coccinea", g:"Quercus", s:"coccinea", nl:"Scharlaken eik",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"15–20 m", breedte:"10–15 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Geelgroene katjes",
  groeivorm:"Boom", groei:"Snel", gebruik:["Park","Solitair","Herfstkleur"],
  onderscheid:"Lijkt op de Amerikaanse eik maar met <b>dieper ingesneden, glanzender blad</b> en de <b>felste scharlakenrode herfstkleur</b> van alle eiken.",
  weetje:"De herfstkleur komt het best op zure, goed doorlatende grond; op kalk verkleurt hij dof." },

{ id:"quercus-frainetto", g:"Quercus", s:"frainetto", nl:"Hongaarse eik",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"20–30 m", breedte:"15–20 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Geelgroene katjes",
  groeivorm:"Boom", groei:"Snel", gebruik:["Laanboom","Park","Straatboom"],
  onderscheid:"<b>Zeer groot blad tot 20 cm met veel diepe, regelmatige lobben</b> — het grootste en meest gelobde eikenblad dat je hier tegenkomt.",
  weetje:"Geldt als een van de beste klimaatbestendige laanbomen: droogtetolerant, stormvast en weinig ziektegevoelig." },

{ id:"quercus-phellos", g:"Quercus", s:"phellos", nl:"Wilgbladige eik",
  standplaats:"Volle zon", water:"Normaal tot vochtig", hoogte:"15–20 m", breedte:"10–15 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Geelgroene katjes",
  groeivorm:"Boom", groei:"Snel", gebruik:["Laanboom","Straatboom","Park"],
  onderscheid:"<b>Smal, gaafrandig blad als van een wilg</b>, zonder enige lob — de meest onverwachte eik van allemaal. Alleen de eikels verraden het geslacht.",
  weetje:"Een geliefde instinker: iedereen zegt wilg, tot er eikels op de grond liggen." },

{ id:"quercus-suber", g:"Quercus", s:"suber", nl:"Kurkeik",
  standplaats:"Volle zon", water:"Droog", hoogte:"10–15 m", breedte:"10–15 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Gele katjes",
  groeivorm:"Boom", groei:"Traag", gebruik:["Solitair","Droge tuin","Kusttuin"],
  onderscheid:"Wintergroen, met <b>dikke, zachte, diep gegroefde kurkschors</b> waar je met je vingers in kan duwen. Blad klein en grijsviltig aan de onderkant.",
  weetje:"Dit is de boom van de kurkstop. Om de negen jaar wordt de bast geoogst zonder dat de boom sterft." },

/* ══════════ LONICERA — kamperfoelie ══════════ */
{ id:"lonicera-nitida", g:"Lonicera", s:"nitida", nl:"Struikkamperfoelie",
  standplaats:"Zon tot schaduw", water:"Normaal", hoogte:"1–1,5 m", breedte:"1–1,5 m",
  blad:"Bladhoudend", bloeitijd:"Mei", bloeikleur:"Onopvallend crèmewit",
  groeivorm:"Heester", groei:"Snel", gebruik:["Lage haag","Vormsnoei","Buxusvervanger"],
  onderscheid:"<b>Heel klein, glanzend wintergroen blaadje</b> van nog geen centimeter, op dichte, stijve twijgen. Lijkt in niets op een klimmende kamperfoelie.",
  weetje:"De belangrijkste buxusvervanger: even knipvast, maar groeit wel drie keer zo snel — dus vaker scheren." },

{ id:"lonicera-sempervirens", g:"Lonicera", s:"sempervirens", nl:"Trompetkamperfoelie",
  standplaats:"Volle zon", water:"Normaal", hoogte:"3–5 m klimmend", breedte:"1–2 m",
  blad:"Halfbladhoudend", bloeitijd:"Juni–september", bloeikleur:"Scharlakenrood met oranje",
  groeivorm:"Klimplant", groei:"Normaal", gebruik:["Pergola","Muurbegroeiing","Vlinderplant"],
  onderscheid:"<b>Lange, smalle, scharlakenrode trompetbloemen zonder geur</b>, in kransen aan het takuiteinde. De bovenste bladparen zijn tot een schijf vergroeid.",
  weetje:"De enige geurloze van het stel: hij mikt niet op nachtvlinders maar op kolibries in zijn thuisland." },

{ id:"lonicera-periclymenum", g:"Lonicera", s:"periclymenum", nl:"Wilde kamperfoelie",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"4–6 m klimmend", breedte:"1–2 m",
  blad:"Bladverliezend", bloeitijd:"Juni–augustus", bloeikleur:"Crèmewit tot roodgeel",
  groeivorm:"Klimplant", groei:"Snel", gebruik:["Pergola","Haag","Vogelbosje","Geurtuin"],
  onderscheid:"Inheemse klimmer met <b>vrije, niet-vergroeide bladparen</b> en sterk geurende bloemen in hoofdjes. Windt zich <b>rechtsom</b> rond zijn steun.",
  weetje:"De geur komt pas 's avonds vrij en trekt pijlstaartvlinders. Waardplant voor het bruin dikkopje en voedsel voor vogels." },

{ id:"lonicera-japonica", g:"Lonicera", s:"japonica", nl:"Japanse kamperfoelie",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"5–8 m klimmend", breedte:"2–3 m",
  blad:"Halfbladhoudend", bloeitijd:"Juni–oktober", bloeikleur:"Wit, verkleurend naar geel",
  groeivorm:"Klimplant", groei:"Snel", gebruik:["Scherm","Pergola","Bodembedekker"],
  onderscheid:"<b>Bloemen per twee in de bladoksels</b>, niet in hoofdjes, en ze <b>verkleuren van wit naar geel</b> — vandaar wit en geel door elkaar in dezelfde plant.",
  weetje:"Bloeit maandenlang en is half wintergroen, maar gedraagt zich in delen van Europa invasief. Bewust inzetten." },

{ id:"lonicera-henryi", g:"Lonicera", s:"henryi", nl:"Wintergroene kamperfoelie",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"5–8 m klimmend", breedte:"2–3 m",
  blad:"Bladhoudend", bloeitijd:"Juni–juli", bloeikleur:"Geelrood",
  groeivorm:"Klimplant", groei:"Snel", gebruik:["Groen scherm","Pergola","Afscherming"],
  onderscheid:"<b>Volledig wintergroen met lang, smal, leerachtig donker blad</b>. De enige echte wintergroene klimmer van het geslacht; bloei is bijzaak.",
  weetje:"Wordt vooral geplant om het hele jaar door een dicht groen scherm te houden, ook in de winter." },

{ id:"lonicera-caprifolium", g:"Lonicera", s:"caprifolium", nl:"Tuinkamperfoelie",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"4–6 m klimmend", breedte:"1–2 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Crèmewit met roze",
  groeivorm:"Klimplant", groei:"Snel", gebruik:["Pergola","Geurtuin","Muurbegroeiing"],
  onderscheid:"<b>De bovenste twee of drie bladparen zijn rond de stengel vergroeid tot één schotel</b>, waar de bloemtros middenin staat. Zeer opvallend kenmerk.",
  weetje:"Bloeit vroeger dan de wilde kamperfoelie en geurt zo mogelijk nog sterker in de avond." },

{ id:"lonicera-xylosteum", g:"Lonicera", s:"xylosteum", nl:"Rode kamperfoelie",
  standplaats:"Zon tot schaduw", water:"Normaal", hoogte:"2–3 m", breedte:"2–2,5 m",
  blad:"Bladverliezend", bloeitijd:"Mei", bloeikleur:"Geelwit, per twee",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Landschap","Vogelbosje","Bosrand","Haag"],
  onderscheid:"<b>Struik, geen klimmer</b>, met dofgroen behaard blad en <b>felrode bessen die per twee aan elkaar zitten</b>. Inheems in bosranden.",
  weetje:"De bessen zijn giftig voor mensen maar worden gretig door vogels gegeten. Het hout is keihard." },

{ id:"lonicera-fragrantissima", g:"Lonicera", s:"fragrantissima", nl:"Winterkamperfoelie",
  standplaats:"Zon tot halfschaduw", water:"Normaal", hoogte:"1,5–2,5 m", breedte:"1,5–2,5 m",
  blad:"Halfbladhoudend", bloeitijd:"December–maart", bloeikleur:"Crèmewit",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Winterbloei","Geurtuin","Border"],
  onderscheid:"Struikvormig en <b>bloeit midden in de winter op kale takken</b>, met kleine crèmewitte bloempjes die <b>zeer sterk naar citroen geuren</b>.",
  weetje:"Zet hem langs een pad dat je in december gebruikt; je ruikt hem vóór je hem ziet." },

{ id:"lonicera-tatarica", g:"Lonicera", s:"tatarica", nl:"Tataarse kamperfoelie",
  standplaats:"Zon tot halfschaduw", water:"Droog tot normaal", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Roze tot wit",
  groeivorm:"Heester", groei:"Snel", gebruik:["Haag","Landschap","Vogelbosje"],
  onderscheid:"Struik met <b>blauwgroen, volledig kaal blad</b> en overvloedige roze bloempjes per twee. Kaler en blauwer dan de rode kamperfoelie.",
  weetje:"Verdraagt droogte en snoei uitstekend; in Noord-Amerika is hij juist een beruchte invasieve soort geworden." },

{ id:"lonicera-korolkowii", g:"Lonicera", s:"korolkowii", nl:"Blauwbladkamperfoelie",
  standplaats:"Volle zon", water:"Droog tot normaal", hoogte:"2–3 m", breedte:"2–3 m",
  blad:"Bladverliezend", bloeitijd:"Mei–juni", bloeikleur:"Roze",
  groeivorm:"Heester", groei:"Normaal", gebruik:["Border","Haag","Droge tuin"],
  onderscheid:"<b>Klein, rond, blauwgrijs viltig behaard blad</b> op sierlijk overhangende takken — de blauwste van het geslacht, van ver herkenbaar aan de kleur.",
  weetje:"Verdraagt hitte en droogte beter dan alle andere kamperfoelies; daarom in opmars in droogtebestendige beplanting." },

];
